manikumarreddyu/AgroTech-AI

README.md
Deployed Backend in Render and Updated README.md for Local Setup
This PR includes the deployment of the backend on Render, along with updates to the README.md file to include steps for setting up and running the Flask backend locally. This ensures clarity for contributors or users who want to run the project both locally and via the deployed version.
#93
- Deployed the Flask backend to Render for remote access.
- Updated the README.md file to include instructions for setup and running the backend locally.
=> Deployed Backend in Render and Updated README.md for Local Setup

frontend/src/components/Footer.jsx, frontend/src/components/Prices.jsx
=> ui part done

frontend/src/MainContent.jsx, frontend/src/components/AIEngine.jsx, frontend/src/pages/Article.jsx, frontend/src/pages/article.css
Replace External Redirection to Tomato Disease Article with Internal Page
This PR replaces the external redirection to the tomato disease article with an internal page on the Agrotech AI platform. The purpose is to enhance user experience by keeping users within the platform and providing consistent access to the article.
Checklist
This change will help in reducing bounce rates and improving platform engagement by keeping users within Agrotech AI.
=> feat:Replacing External Redirection to Tomato Disease Article with Internal Page

frontend/src/App.jsx, frontend/src/MainContent.jsx, frontend/src/components/AIEngine.jsx, frontend/src/components/Disease.jsx, frontend/src/components/Submit.jsx
Frontend for Sugarcane Disease Prediction Backend
This PR introduces significant changes to the frontend for the crop disease prediction feature, specifically for sugarcane. It also enhances the crop selection process and introduces dedicated engine pages for each crop. Image uploads are dynamically routed to the corresponding backend based on the selected crop.
closes: #157 
- **Revamped Crop Selection Page**: 
- Redesigned the layout and UI to make the crop selection process more intuitive and visually appealing.
- **Dedicated Engine Pages for Each Crop**:
- Each crop now has its own page with relevant disease necessities and prevention tips.
- **Dynamic Image Upload**: 
- Image uploads are now routed to different backends depending on the crop selected (e.g., sugarcane images are sent …
=> Add Frontend for Sugarcane Disease Prediction Backend

frontend/src/pages/ChatBot.jsx
Improve Message Popup
Improve Message Popup
#307
Improve Message Popup
=> Improve Message Popup for Chatbot

frontend/src/pages/ChatBot.jsx
Enhanced styles and formatting
Enhanced styles and formatting
#308
Enhanced styles and formatting
=> Enhanced styles and formatting

frontend/src/components/GoogleTranslate.jsx
Remove Empty `div` in GoogleTranslator Component to Fix Navbar UI Disturbance
This pull request addresses the issue of an empty `div` present in the `GoogleTranslator` component, which was causing visual disturbances and layout issues in the navbar. The unnecessary `div` has been removed to ensure a cleaner UI and improved alignment of the navbar.
Fixes #327 
- Removed the empty `div` from the `GoogleTranslator` component.
- Verified that the navbar UI is now displaying correctly without any disturbances.
- Previously
- Now
=> [FIX] : Remove Empty `div` from GoogleTranslator Component

seed-qual-predictor/README.md, seed-qual-predictor/app.py, seed-qual-predictor/requirements.txt
Added Seed Quality Prediction Model for maize seeds
This is a Flask-based API for predicting maize seed quality using a CNN model. It includes the model (`model.h5`), endpoints for image upload and classification, and a `/predict` route to return seed quality (broken, discolored, or pure) along with confidence scores. Basic file structure and necessary setup for deployment using Gunicorn are also provided.
Fixes #303 
I tested it using POSTMAN and I am excited to share that it is working fine!
=> Added Seed Quality Prediction Model

frontend/package-lock.json, frontend/src/components/Fertilizer.jsx
Fixed the Bug of Visibility for Soil Type and Crop Type by Changing Colors According to Dark Mode
This PR addresses a bug where the visibility of the Soil Type and Crop Type sections was compromised in dark mode. The color scheme has been updated to ensure text and background elements are clearly visible in both light and dark modes.
#349
- Updated the color scheme for the Soil Type and Crop Type sections.
- Improved the contrast between text and background for dark mode.
- Ensured the colors adapt dynamically when switching between light and dark modes.
The color updates were made to ensure accessibility and improve user experience in dark mode. Please verify if other components are affected by this update.
Footer
=> Fixed the Bug of visibility of Soil Type and Crop Type by changing the colors according to the dark mode

frontend/src/components/tools/CropYield.jsx, frontend/src/components/tools/FertilizerRequirement.jsx, frontend/src/components/tools/SoilMoisture.jsx, frontend/src/components/tools/WaterRequirement.jsx
Fixed the margin and heading styles for the calculator components which were not rendering properly.
This PR fixes that the margin in the calculator components was not set properly due to which it hid the heading of the calculator and even the labels of the form. Also the headings have been given a style consistent to other headings in the app.
Fixes #403
-added styles for the headings of the calculator consistent with the app theme.
-added consistent styling to the labels of the forms.
-made the bg color of all calculators consistent.
-changed the margins of the calculators.
|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
|  ![Original screenshot](https://github.com/user-attachments/assets/154fcd9a-cd23-4a9b-995 …
=> Fix/adjust UI alignment for tools

frontend/src/components/Navbar.jsx
https://github.com/user-attachments/assets/7d447d6d-817b-420a-b054-e83cd6385ccd
Footer
=> added hovereffect at dropdown navlink for desktop

frontend/package-lock.json, frontend/package.json, frontend/src/components/models/Fertilizer.jsx
Fertilizer Prediction Page
View Report and Download pdf button functioning in fertilizer prediction page
This PR introduces a feature to view and download a fertilizer prediction report based on the form inputs and prediction result. The report is displayed on the page when the user clicks the "View Report" button, and it includes details such as temperature, humidity, soil type, and prediction results. Users can also download the report as a PDF using the "Download PDF" button.
Fixes ##583
- Implemented a  button for "View Report" that conditionally renders the report on the page.
- Installed npm package for jspdf ['npm i jspdf']
- Integrated jsPDF for generating and downloading the report in PDF format.
Installed npm package for jspdf in fronted folder
=>  View Report and Download pdf button functioning in fertilizer prediction page

frontend/src/components/models/Fertilizer.jsx
Phosphorous level in Fertilizer Page
In Fertilizer prediction page , while entering phosphorous level in prediction form , it doesn't show phosphorous level range , so this PR adds phosphorous level.
Fixes #626
- Added logic to dynamically assign text colors to nutrient titles.
- Implemented Tailwind CSS classes for green (`text-green-500`), blue (`text-blue-500`), and orange (`text-orange-500`) based on the nutrient type.
- Improved code readability by refactoring the conditional `className` assignment.
Footer
=> Phosphorous level in Fertilizer Page

backend/controllers/agriProductController.js, backend/middleware/authMiddleware.js, backend/model/AgriProduct.js, backend/routes/agriProductRoutes.js
Creating Backend Schema For Rental and Lease products
Referenced many other applications as suggested by the admin and creating AgriProductSchema along with controllers, middleware, routes. 
https://github.com/MohamedAmineALLAF/MERN_car_rental
https://github.com/VaibhavArora314/StyleShare
This schema represents agricultural products that users can list, including categories like equipment, land, seeds, and fertilizers. It supports various transaction types such as rent, lease, sale, or purchase and includes fields for product details, location, availability, and more.
- **Type**: `ObjectId` (Reference to the `User` model)
- **Description**: References the user (typically a farmer or vendor) who owns or has listed the product.
- **Type**: `String`
- **Description**: The name of the …
=> Creating Backend Schema For Rental and Lease products

backend/controllers/authController.js, backend/controllers/contactusController.js, backend/controllers/userController.js, backend/routes/Contactroute.js, backend/routes/auth.js, backend/routes/users.js
This PR separates the routes and controllers in the backend of the project.
Footer
=> separate routes and controllers

backend/controllers/authController.js, frontend/src/components/LoginPage.jsx, frontend/src/context/AuthContext.jsx
This pull request addresses two significant issues regarding user authentication:
- Login State Persistence: Users are logged out after refreshing the page due to the login state not being stored in local storage.
- User Data Return: The backend does not return the user data after a successful login, hindering proper user session management.
- Frontend Adjustments
- Updated the authentication context to check local storage for existing login state upon initialization.
- Ensured user data is retrieved and stored in context after login.
- Backend Adjustments
- Modified the signinController to return user id along with the token upon successful authentication.
- Closes #705 
https://github.com/user-attachments/assets/f296bf84-79b4-4f50-8823-b9ad162d3885
=> [Fixed] Login State Persistence and User Data Return on Login

backend/controllers/authController.js, backend/model/user.js, backend/routes/auth.js, frontend/src/MainContent.jsx, frontend/src/components/EmailVerification.jsx, frontend/src/components/SignUpPage.jsx
Email verification while signup
Email is sent to the mail id of the user that he enters while verifying the otp and the account gets verified.
wrote and modified the backend APIs and created a new page on the frontend to verify the otp.
fixes #734 
wrote and modified the backend APIs and created a new page on the frontend to verify the otp.
https://github.com/user-attachments/assets/b9a63fee-a2ca-4eae-8449-17ec7cda68b0
Footer
=> Add email verification 

frontend/src/components/models/Fertilizer.jsx
Fix #747 
Remove the Dark Mode and Chatbot
Remove the Dark Mode and Chatbot
fix #747
=> Remove the Dark Mode and Chatbot | Issue #747

Docker-compose.yml, backend/Dockerfile, frontend/Dockerfile
Creating docker containerization for agrotech frontend and backend
This PR adds the docker containerization so that the application can run inside the docker environment on any machine.
Command to build and run the docker image : docker compose up --build
Created Dockerfiles and Docker-compose.yml
=> Add Docker Containerization

backend/controllers/discussionController.js, backend/index.js, backend/model/comment.js, backend/model/post.js, backend/routes/discussionRoutes.js
Write the backend for discussion forum for farmers.
Added the routes, controllers and models necessary for discussions.
=> Add discussion APIs

backend/controllers/shop/utilityController.js, backend/routes/shop.js, frontend/src/AgroShopAI/components/ShopNavbar.jsx, frontend/src/AgroShopAI/components/sub-components/SearchBar.jsx
This pull request implements feature to search products in Search bar of the application, enhancing its functionality and user experience. The updates include the addition of a debouncing feature, integration with a newly created API, and improved navigation to product details upon selection.
- Closes #758 
**Features Added:**
1. **Debouncing Functionality:** 
- Added a debouncing mechanism to optimize search requests.
2. **Dynamic Search Results:**
- Integrated the following API endpoint to fetch search results based on user queries: 
- **Endpoint:** `/api/search?query=${searchQuery}`
3. **Navigation to Product Details:**
- Users can now navigate to a dedicated product details page when a search result is clicked.
4. **Improved User Interface:** 
- Enhanced styling for the dropdown …
=> Added Complete Functionality to Search Bar

backend/index.js, frontend/src/AgroRentAI/NavigateProducts.jsx, frontend/src/AgroRentAI/components/AgriProductListing.jsx, frontend/src/components/Footer.jsx, frontend/src/components/ForgotPassword.jsx, frontend/src/components/SignUpPage.jsx, frontend/src/pages/Contact.jsx
Merge it once and check if the problem still persists
Closes #802
=> Fixed vercel Backend Login issue

frontend/package-lock.json, frontend/src/AgroRentAI/RentAdminDashboard.jsx, frontend/src/MainContent.jsx
Admin Dashboard
Product Management: Add, update, and delete listings, including details like images, prices, categories, and availability.
Order Management: View, approve, and manage all rentals, including tracking returns and cancellations.
User Management: Manage customer profiles, respond to inquiries, and review feedback.
Analytics & Reporting: View metrics on popular equipment, rental frequency, revenue, and user behavior.
Notifications: Send automated reminders to users about upcoming rental returns, overdue items, and payment confirmations.
https://github.com/user-attachments/assets/3d350dc9-4850-4665-8736-3b7c80aae5c5
=> Add admin dashboard

backend/package-lock.json, frontend/package-lock.json, frontend/src/AgroRentAI/NavigateProducts.jsx, frontend/src/AgroRentAI/RentProductDetails.jsx, frontend/src/MainContent.jsx
Details Page.
This PR creates a new product details page for renting of products and also integrated the call with the backend API to show real time product details from the database.
The product details can be navigated by clicking the rent now button on product cart.
Wrote ApiUrl to dynamically changes between production and local development environement.
https://github.com/user-attachments/assets/e5df658a-f9f9-4cca-b894-db4c3c896b73
=> Add RentProduct details

frontend/src/AgroShopAI/components/Pages/Order-history.jsx
This PR introduces an order history page specifically designed for admins. The page will display a list of all orders with status tags such as "Pending," "Complement," "Processing," "Completed," and others. These tags will help admins easily track the progress and status of each order in the system. 
The page includes:
- A table of orders with detailed status.
- Status tags (e.g., Pending, Processing, Complement, Completed) displayed next to each order.
- Sorting and filtering options to view orders by specific statuses or other criteria.
- A new page has been created to display a history of all orders placed on the platform. The page is accessible to admins only.
- Each order is displayed with:
- Order ID
- Customer Name
- Date of Order
- Status Tag (e.g., Pending, Complement, …
=> Add Order History Page with Status Tags for Admin

backend/controllers/shop/sub-controllers/orderController.js, backend/controllers/shop/sub-controllers/orderTrackingController.js, backend/model/shop/sub-model/OrderHistory.js, backend/model/shop/sub-model/OrderTracking.js
This PR introduces the implementation of the **Order Tracking System** for better management of orders within the application. It includes the creation of the **Order Tracking Schema** along with the necessary **controllers** to handle various order-related operations.
---
- **Order Tracking Schema:**
- Created a new Mongoose schema to represent order information including:
- Customer details
- Order items
- Order status
- Order timestamps (for creation, updates, and delivery)
- **Controllers Implemented:**
1. **createOrder:** Handles the creation of new orders in the system.
2. **getOrders:** Fetches all orders.
3. **updateOrderStatus:** Allows updating the order's current status (e.g., "pending", "shipped", "delivered").
4. **deleteOrder:** Deletes a specific order from the system.
5. …
=> Added Order Tracking Schema and Controllers with advance features

backend/controllers/shop/sub-controllers/orderController.js, backend/model/shop/sub-model/OrderHistory.js
This PR introduces the `Order` schema to the application, along with the following controllers for order management:
- `updateOrderItemQuantity`
- `removeItemFromOrder`
- `addItemToOrder`
- `getOrderById`
- `deleteOrder`
- `updateOrderStatus`
- `getOrders`
- `createOrder`
- `bulkUpdateOrderStatus`
- `getOrderStatusHistory`
- `getOrdersByStatus`
- `getAllOrdersForAdmin`
These changes provide the necessary logic and structure for managing orders within the system, supporting both individual and bulk actions, as well as facilitating administrative control over order status.
- A new schema `Order` has been added to the database to manage the order details, including item information, customer details, order status, and timestamps.
- **`updateOrderItemQuantity`**: Updates the quantity of a …
=> Add Order Schema and CRUD Controllers

backend/controllers/shop/sub-controllers/returnController.js, backend/model/shop/sub-model/ReturnProduct.js, backend/routes/sub-routes/returnRoutes.js
This pull request implements the product return feature, which includes the creation, management, and tracking of product return requests. The functionality allows users to initiate return requests, admins to approve or reject them, and users to track their return history. The following routes and schema have been added to manage product returns effectively.
---
1. **POST /api/returns** - Create a return request
2. **PATCH /api/returns/:id** - Update the return status (admin only)
3. **GET /api/returns/:id** - Get detailed information of a return request
4. **GET /api/returns/user/:userId** - Get the return history of a user
5. **GET /api/returns/pending** - Get all pending return requests (admin only)
6. **PATCH /api/returns/cancel/:id** - Cancel a return request
7. **GET …
=> Implemented Product Return Feature with routes, schema and Controllers for advance feature

frontend/src/AgroShopAI/components/Pages/DiscountCouponManagement.jsx, frontend/src/AgroShopAI/components/Pages/components/CouponForm.jsx, frontend/src/AgroShopAI/components/Pages/components/CouponTable.jsx, frontend/src/AgroShopAI/components/Pages/components/DeleteConfirmationModal.jsx, frontend/src/AgroShopAI/components/Pages/components/FilterBar.jsx
This PR introduces a new feature for creating and editing coupon codes. It includes a form that allows users to input details for new coupons or edit existing ones. The form fields include coupon code, description, value, minimum order amount, maximum discount, start and end dates, and usage limit. The feature is designed to be flexible and user-friendly, providing easy creation and management of coupon codes.
1. **Coupon Form Component**:
- Created a `CouponForm` component responsible for displaying the coupon creation/edit form.
- Added various input fields:
- Coupon `code` (text input)
- Coupon `description` (text input)
- `value` (text input)
- `minOrderAmount` (text input)
- `maxDiscount` (text input)
- `startDate` (date input)
- `endDate` (date input)
- `usageLimit` (text input)
- …
=> Implemented Coupon Management with Coupon Creation and Edit Feature

frontend/src/AgroShopAI/components/Pages/ReturnPage.jsx, frontend/src/AgroShopAI/components/Pages/components/ReturnFilter.jsx, frontend/src/AgroShopAI/components/Pages/components/ReturnHeader.jsx, frontend/src/AgroShopAI/components/Pages/components/ReturnHistory.jsx, frontend/src/AgroShopAI/components/Pages/components/ReturnModal.jsx, frontend/src/AgroShopAI/components/Pages/components/ReturnProductCard.jsx
This PR introduces a comprehensive "Return Page" designed for users to view, manage, and initiate product returns. The page provides a detailed layout of all return-related functionalities, allowing users to track previous returns, initiate new ones, and receive real-time updates on the status of each return.
1. **Return History Overview**:
- Displays a summary list of all past returns, with essential details like product name, return date, status, and comments. This helps users quickly review their return activities.
2. **New Return Request Form**:
- Includes an easy-to-use form for initiating a new return. Users can select the product they wish to return, choose reasons from a dropdown, add optional comments, and upload photos if required.
3. **Return Status Tracking**:
- Provides …
=> Add Full "Return Page" for Tracking and Managing Product Returns

frontend/src/AgroShopAI/components/Pages/Admin-Dashboard.jsx, frontend/src/AgroShopAI/components/Pages/components/Analysis.jsx, frontend/src/AgroShopAI/components/Pages/components/PopularProducts.jsx, frontend/src/AgroShopAI/components/Pages/components/SalesTrend.jsx, frontend/src/AgroShopAI/components/Pages/components/Sidebar.jsx, frontend/src/AgroShopAI/components/Pages/components/StatCard.jsx, frontend/src/AgroShopAI/components/Pages/components/StatisticComponent.jsx, frontend/src/AgroShopAI/components/Pages/components/TimeRangeSelector.jsx, frontend/src/AgroShopAI/components/Pages/components/UserRegistrations.jsx, frontend/src/MainContent.jsx
This PR introduces a new **Statistics Dashboard** for the Admin Panel, which provides an overview of key metrics and insights, including:
- **Time Range Selector**: Allows admins to switch between daily, weekly, or monthly statistics.
- **Stat Cards**: Displays key metrics such as total users, active sellers, total sales, pending orders, and total products.
- **Sales Trend Chart**: Visualizes sales performance over time.
- **User Registration Trend**: Shows the number of user registrations over the selected time range.
- **Popular Products**: Lists the top-selling products in the selected period.
- **Analysis**: Provides a brief analysis of the trends (e.g., whether sales or registrations are increasing or decreasing).
1. **Added New Components:**
- `StatisticComponent`: The main …
=> Added Statistics Dashboard to Admin Dashboard with Analytical Tools

frontend/src/AgroShopAI/components/Pages/SellerDashboard.jsx, frontend/src/AgroShopAI/components/Pages/components/AboutUsSection.jsx, frontend/src/AgroShopAI/components/Pages/components/PolicySection.jsx, frontend/src/AgroShopAI/components/Pages/components/ProfileSection.jsx, frontend/src/AgroShopAI/components/Pages/components/SellerSettingsPage.jsx
This PR adds a **Seller Settings Page** to the seller dashboard. The settings page includes sections for updating profile information, about us details, and policies (shipping, returns, and support). It allows the seller to toggle between edit and view modes for each section and saves the changes locally. The layout is responsive and designed for easy navigation and user experience.
- Closes #900 
- **SellerSettingPage**: A new page component for managing seller settings, including profile, about us, and policy information.
- **ProfileSection**: Component to handle profile information (business name, tagline, email, location, etc.), with file upload functionality for changing profile pictures.
- **AboutUsSection**: Component to manage the "About Us" section, allowing text editing.
- …
=> Added Customisable Seller Bio and Transparent Store Policies for Enhanced Buyer Trust

backend/controllers/rent/RentalController.js, backend/index.js, backend/model/rent/rentProduct.js, backend/model/user.js, backend/routes/rent/rentalRoutes.js
Renting APIs for products
Renting Agricultural Equipment
Endpoint: POST /rentals
Updating Rental Details
Endpoint: PUT /rentals/{rentalId}
Cancelling a Rental
Endpoint: DELETE /rentals/{rentalId}
Viewing Rental Details
Endpoint: GET /rentals/{rentalId}
Returning Rented Equipment
Endpoint: POST /rentals/{rentalId}/return
RentProduct Schema:
Added rental price fields for different durations: rentalPricePerHour, rentalPricePerDay, rentalPricePerWeek, rentalPricePerMonth.
Introduced availabilityStatus to track product rental status ('available', 'rented', 'maintenance').
Included rentedQuantity to track how many items of the product have been rented.
User Schema:
Rentals array stores rental data with rentalId, product, quantity, rentalDuration, and rental status.
Rental Controller: …
=> Add rental APIs

frontend/src/AgroShopAI/components/Pages/SellerDashboard.jsx, frontend/src/AgroShopAI/components/Pages/components/CsvUpload.jsx, frontend/src/AgroShopAI/components/Pages/components/NavigationButtons.jsx, frontend/src/AgroShopAI/components/Pages/components/ProductEntry.jsx, frontend/src/AgroShopAI/components/Pages/components/ProductStepForm.jsx, frontend/src/AgroShopAI/components/Pages/components/SellerNav.jsx
This PR introduces a new feature for the **Agroshop Seller Dashboard**. It adds the **Product Entry** page, allowing sellers to add new products by providing details such as product name, category, price, quantity, and description. 
The page is designed as a multi-step form with the following steps:
1. **Step 1**: Product Name and Category.
2. **Step 2**: Product Price and Quantity.
3. **Step 3**: Product Description (with a custom confirmation modal for product review before submission).
The form includes basic validation, and on submitting the product details, the data is logged to the console and an alert is triggered.
Additionally, the page includes the functionality for CSV file uploads for bulk product entry. The CSV file is processed, and validation errors (if any) are shown. Upon …
=> Added "Product Entry" Page to Seller Dashboard with Bulk Upload feature

backend/controllers/shop/sub-controllers/inventoryController.js, backend/middleware/sub-ware/inventoryMiddleware.js, backend/model/shop/sub-model/InventoryModel.js
This PR implements the Inventory Management module, which includes schema definitions and controllers for managing product stock, inventory across different warehouses, and automatic reorder processes when stock levels fall below predefined thresholds. Key features and functionalities include:
1. **Inventory Schema:**
- `productId`: Reference to the `Product` collection to associate each inventory item with a product.
- `currentStockLevel`: Integer to track the current quantity of the product in stock.
- `reorderLevel`: Minimum threshold for each product, below which an automatic reorder or alert is triggered.
- `lastRestockedDate`: Date field to track the last restocking event.
- `warehouseLocation`: Tracks which warehouse the product is stored in.
- `supplierId`: (Optional) Reference to …
=> Complete Inventory Management Module Implementation

backend/controllers/shop/sub-controllers/warehouseController.js, backend/middleware/sub-ware/warehouseMiddleware.js, backend/model/shop/sub-model/Warehouse.js
This PR introduces a comprehensive set of controllers to handle warehouse management functionality. The module is designed to support key operations such as warehouse creation, updates, deletion, inventory management, and capacity checks. These controllers enable the system to manage warehouse data effectively.
1. **`createWarehouse`**  
- This controller is responsible for creating a new warehouse. It validates that the `warehouseId` and `warehouseName` are unique to ensure no duplicates exist.
- Upon successful validation, a new warehouse is created with the given details and saved to the database.
2. **`updateWarehouse`**  
- Allows the updating of an existing warehouse by modifying its attributes such as `warehouseName`, `address`, `capacity`, `currentOccupancy`, and `contactInfo`.
- …
=> Added Warehouse Management Module with Controllers, Middleware, and Schema

frontend/src/AgroRentAI/RentAdminDashboard.jsx, frontend/src/AgroRentAI/components/AdminCustomerSupport.jsx, frontend/src/AgroRentAI/components/AdminMarketing.jsx, frontend/src/AgroRentAI/components/AdminReport.jsx, frontend/src/AgroRentAI/components/AdminSalesAnalytics.jsx, frontend/src/AgroRentAI/components/AdminSecurity.jsx, frontend/src/AgroRentAI/components/AdminSettings.jsx
Extended Admin Dashboard
This PR adds the following areas in the Admin Dashboard 
Sales & Revenue Analytics: View sales trends, top products, and revenue reports.
Marketing & Promotions: Manage discounts, campaigns, and promotional offers.
Customer Support & Reviews: Handle feedback, support tickets, and review moderation.
Settings & Configuration: Adjust payment, shipping, tax, and notification settings.
Reports and Data Export: Generate and export custom reports on users and sales.
Security & Audit Logs: Track admin activities, permissions, and login records.
Use Case
https://github.com/user-attachments/assets/f39dec68-0bc1-4dec-a189-678cb962467c
=> extend admin dashboard 

frontend/src/pages/Contact.jsx
fix #826 
Contact Page Revamped
1. Services Details Card Added.
2. Revamp Contact Us Page
3. FAQs Section Removal (As Already Present on Home Page).
4. Testimonials Card Added.
5. Newsletter Added.
=> Contact Page Revamped | Issue #826

frontend/src/AgroShopAI/components/Pages/GiftBenefit.jsx, frontend/src/AgroShopAI/components/Pages/GiftCard.jsx, frontend/src/AgroShopAI/components/Pages/GiftFaq.jsx, frontend/src/AgroShopAI/components/Pages/GiftIdeas.jsx, frontend/src/AgroShopAI/components/Pages/GiftLetter.jsx, frontend/src/AgroShopAI/components/Pages/GiftTest.jsx, frontend/src/MainContent.jsx
This PR adds a new `GiftCard` page to the application. The page has been divided into individual, modular components for clarity, each representing a specific feature. The `GiftCard` page is designed with a user-friendly layout and includes features such as a form for purchasing gift cards, promotional banners, gift ideas, and featured products. 
1. **GiftCard Page Layout and Structure**
- Created a dedicated `GiftCard.js` page to serve as the main layout for the gift card functionality.
- Organized the page using modular components for maintainability and a clear, intuitive layout for end-users.
2. **Modular Components Added**
- **`Header`**: 
- Displays a prominent header introducing the gift card section.
- Provides an engaging first impression and encourages users to explore gift card …
=> Added GiftCard page with full features and modular components

frontend/src/AgroShopAI/components/Pages/Admin-Dashboard.jsx, frontend/src/AgroShopAI/components/Pages/ReturnPage.jsx, frontend/src/AgroShopAI/components/Pages/components/ReturnAdminFilter.jsx, frontend/src/AgroShopAI/components/Pages/components/ReturnAdminHeader.jsx, frontend/src/AgroShopAI/components/Pages/components/ReturnAdminHistory.jsx, frontend/src/AgroShopAI/components/Pages/components/ReturnAdminModal.jsx, frontend/src/AgroShopAI/components/Pages/components/ReturnAdminProductCard.jsx, frontend/src/AgroShopAI/components/Pages/components/ReturnPage.jsx, frontend/src/AgroShopAI/components/Pages/components/Sidebar.jsx
This pull request addresses the issue of implementing a comprehensive **Return Panel** for admins to manage return and refund requests submitted by users. The admin panel provides functionality for viewing, approving, rejecting, and processing requests, with complete details of the requests, user information, and product information. The panel also includes features to filter, sort, and update the status of requests.
- Created a responsive layout for the return and refund requests page.
- Each request displays the following information:
- **User Information**: Name, contact details.
- **Order & Product Information**: Order ID, product name, quantity, and price.
- **Reason for Return/Refund**: The reason submitted by the user.
- **Request Submission Date**: The date the request was …
=> Implement Return Panel for Managing Return and Refund Requests

backend/controllers/shop/sub-controllers/adminController.js, backend/controllers/shop/sub-controllers/paymentController.js, backend/middleware/sub-ware/validatePaymentInvoice.js, backend/model/shop/sub-model/payment.js, backend/routes/sub-routes/paymentRoutes.js
This PR introduces the schema, controller, and management features for handling payments in the backend. It includes a set of routes allowing the system to store, track, and manage payment-related information. Additionally, certain CRUD operations are restricted to admins, ensuring secure access and control over payment details via the admin dashboard.
- **Schema Design**: Created a `Payment` schema to store all relevant information about customer payments.
- **Fields**: 
- `paymentId`, `orderId`, `userId`, `amount`, `paymentMethod`, `paymentStatus`, `paymentDate`, `transactionId`.
- **Validations & Defaults**:
- `paymentStatus` defaults to `Pending`.
- Required validations on fields like `amount`, `userId`, and `orderId` to ensure data integrity.
- **CRUD Operations**:
- …
=> Add Payment Schema, Controllers, and Admin-Restricted Management Routes for Backend

backend/controllers/shop/sub-controllers/invoiceController.js, backend/model/shop/sub-model/invoice.js, backend/routes/sub-routes/invoiceRoutes.js
**Description**:
This PR introduces the complete invoice management system, including the schema, routes, and controllers. The system allows for efficient management of invoices within the application, with the ability to generate, update, retrieve, and delete invoices. The following updates have been made:
The `Invoice` schema has been created with the following key fields:
- **invoiceId**: A unique identifier for the invoice.
- **orderId**: A reference to the related order.
- **userId**: A reference to the user associated with the order.
- **amount**: The total amount for the invoice.
- **invoiceDate**: The date when the invoice was generated.
- **dueDate**: The date by which the invoice must be paid.
- **status**: The payment status of the invoice (either "Paid" or "Unpaid").
- …
=> Added Comprehensive Invoice Management System with Routes, Controllers, and Bulk Operations

frontend/src/AgroShopAI/components/Pages/Admin-Dashboard.jsx, frontend/src/AgroShopAI/components/Pages/ProductForm.jsx, frontend/src/AgroShopAI/components/Pages/ProductList.jsx, frontend/src/AgroShopAI/components/Pages/ProductManagement.jsx, frontend/src/AgroShopAI/components/Pages/components/Header.jsx, frontend/src/AgroShopAI/components/Pages/components/Sidebar.jsx
This PR introduces a dedicated admin page for product creation and updates. The page allows administrators to efficiently manage products, including adding new products, updating existing ones, and handling product images. The implementation includes form validation, image upload functionality, and responsive design to enhance the user experience.
1. **Product Creation Form:**
- Admins can add new products to the inventory.
- Form fields include:
- Product Name (Text input)
- Category (Dropdown for category selection)
- Price (Numeric input with currency formatting)
- Description (Text area for detailed product information)
- SKU (Stock Keeping Unit for product tracking)
- Stock Quantity (Numeric input for available stock)
- Product Images (Support for multiple image uploads)
2. **Product …
=> Developed a Dedicated Admin Page for Product Creation and Updates

frontend/src/AgroShopAI/components/Pages/Trending.jsx, frontend/src/AgroShopAI/components/Pages/components/Banner.jsx, frontend/src/AgroShopAI/components/Pages/components/ProductGrid.jsx, frontend/src/AgroShopAI/components/Pages/components/SearchAndSort.jsx, frontend/src/AgroShopAI/components/Pages/components/THeader.jsx, frontend/src/AgroShopAI/components/Pages/components/TProductCard.jsx, frontend/src/MainContent.jsx
**Description**:
This pull request introduces a new **Trending Products Page** that includes a search bar, sorting functionality, and a grid of product cards displaying trending agricultural products. The page is broken into modular components for better maintainability.
- **Header Component**: Added a simple header with the website title.
- **Banner Component**: Added a promotional banner showcasing the trending products section.
- **SearchAndSort Component**: Implemented a search bar for filtering products and a dropdown for sorting products by price, rating, and trending status.
- **ProductCard Component**: Created a reusable product card to display product details like image, name, price, rating, and reviews.
- **ProductGrid Component**: Added a product grid to display all products as …
=> Added Trending Products Page with Search, Sort, and Product Grid

frontend/src/AgroRentAI/RentAdminDashboard.jsx, frontend/src/AgroRentAI/components/AdminUserManagement.jsx
User Management for Admin Frontend 
This  PR add user management functionalities mentioned below:
Admin Dashboard for User Overview: Display a user list with filters (e.g., by role or status) and search options.
Detailed User Profile View: Each profile shows user info, role, permissions, and recent activity logs, with edit options for the admin.
Role and Permission Management: Interface for modifying user roles and permissions with clear labels and dropdowns.
Account Status Toggle: Allow admins to suspend/reactivate accounts with a visual indicator for the account’s current status.
fixes #914 
https://github.com/user-attachments/assets/80198a9e-96c8-433d-a01c-242616db1e35
=> Add user management

frontend/src/components/help/Climate.jsx
Fixed climate location search + added debounce
Fixes #907
https://github.com/user-attachments/assets/187d153e-6091-4c38-89af-f64e16fd3a9b
=> Fixed climate location search + added debounce

backend/controllers/shop/sub-controllers/loyaltyPointsController.js, backend/model/shop/sub-model/loyaltyPointModel.js, backend/routes/rent/analyticsRoutes.js, backend/routes/sub-routes/loyaltyPointsRoutes.js
This PR adds the schema, controller, and routes needed to implement a loyalty points system. The system enables users to earn, manage, and redeem loyalty points based on eligible actions within the application, such as purchases.
---
1. **Loyalty Points Schema**  
The `LoyaltyPoints` schema defines the structure for storing loyalty points for each user. This schema includes:
- **`userId`**: (ObjectId) A reference to the user who has earned the points, allowing connection with the user database.
- **`points`**: (Number) The total points awarded for a specific action.
- **`earnedBy`**: (String) The source or action for earning points, such as `"purchase"` or other actions defined in the application.
- **`timestamp`**: (Date) The date and time when the points were awarded to track the user's …
=> Implemented Loyalty Points System with Schema, Controllers, and Routes

backend/controllers/shop/sub-controllers/referralController.js, backend/model/shop/sub-model/Referral.js, backend/routes/sub-routes/referralRoutes.js, backend/services/sub-service/logger.js, backend/services/sub-service/referralFunc.js, backend/services/sub-service/referralUtils.js
This PR introduces the `Referral` schema, controller, and routes to handle referral functionalities in the application. It includes logging for important actions and a utility function to generate unique referral codes.
- Closes #961 
The `Referral` schema defines the necessary fields for tracking referrals:
- **referralCode**: A unique code generated for each referral.
- **referrerId**: User ID of the person who created the referral code.
- **refereeId**: ID of the user who uses the referral code, if applicable.
- **status**: Status of the referral (e.g., `pending`, `completed`, `expired`).
- **expiryDate**: Date when the referral expires.
- **createdAt** and **updatedAt**: Timestamps for tracking referral lifecycle.
1. **`POST /api/referrals`**: 
- **Controller**: `createReferral`
- …
=> Implement Referral System with Schema, Controllers, Routes, and Logging

backend/controllers/shop/sub-controllers/giftCardController.js, backend/middleware/sub-ware/giftCardMiddleware.js, backend/model/shop/sub-model/GiftCard.js, backend/routes/sub-routes/giftCardRoutes.js, backend/services/sub-service/giftCardUtils.js
This PR implements a comprehensive gift card system for managing gift cards in the application. The system includes the following key functionalities:
1. **Schema:** A schema to store gift card details such as card number, value, status (active, redeemed, expired), user association, and expiry date.
2. **Controller:** Logic for creating, activating, redeeming, and fetching gift card details.
3. **Middleware:** Validation middleware to check the validity and status of gift cards before redemption.
4. **Routes:** API routes to handle creating, redeeming, and managing gift cards.
- closes #962 
1. **POST /api/gift-cards:**
- **Description:** Creates a new gift card with the specified value, associated user ID, and expiry date.
- **Request Body:**
- `value`: The monetary value of the gift …
=> Implemented Gift Card System with Creation, Redemption, and Management Features

frontend/src/AgroShopAI/components/Pages/ConfirmationMessage.jsx, frontend/src/AgroShopAI/components/Pages/TicketDetailModal.jsx, frontend/src/AgroShopAI/components/Pages/TicketFilters.jsx, frontend/src/AgroShopAI/components/Pages/TicketForm.jsx, frontend/src/AgroShopAI/components/Pages/TicketList.jsx, frontend/src/AgroShopAI/components/Pages/TicketUser.jsx, frontend/src/AgroShopAI/components/Pages/Ticketbanner.jsx, frontend/src/MainContent.jsx
This PR introduces the complete support page for managing tickets, including the following features:
- **Header Banner**: A flashy, animated banner with a gradient background and a "Get Help Now" button.
- **Ticket Submission Form**: Allows users to submit new tickets with a subject, description, and priority level.
- **Ticket Filters**: Enables filtering tickets by status, priority, and search term.
- **Ticket List**: Displays a list of tickets with key details such as ID, subject, status, priority, agent, and creation date.
- **Ticket Detail Modal**: Shows additional information about a selected ticket.
---
1. **Header Banner**:
- Introduced a vibrant, animated header banner with a gradient background.
- The banner includes a heading, a description, and a "Get Help Now" …
=>  Added Ticket Page with Ticket Management, Filters, and Header Banner

frontend/src/AgroShopAI/components/Pages/AdminTicket.jsx, frontend/src/AgroShopAI/components/Pages/AdminTicketDetails.jsx, frontend/src/AgroShopAI/components/Pages/AdminTicketList.jsx, frontend/src/AgroShopAI/components/Pages/THeader.jsx, frontend/src/AgroShopAI/components/Pages/TSearchAndFilter.jsx, frontend/src/MainContent.jsx
This pull request introduces the complete Ticket Management System page for the AgroShop admin portal. The page includes the following features:
1. **Enhanced Header**: A visually dynamic header with a gradient background, responsive typography, and hover effects.
2. **Ticket Table**: A table displaying the ticket data with essential fields like `Ticket ID`, `Status`, `Priority`, `Assigned To`, and `Created At`.
3. **Search Functionality**: A search input that allows admins to search through the tickets by various parameters like `Ticket ID`, `Status`, etc.
4. **Filters**: Dropdown filters for sorting tickets based on `Status`, `Priority`, and `Assigned To`.
5. **Pagination**: A pagination feature for navigating through multiple pages of tickets.
6. **Action Buttons**: Buttons for …
=> Implemented Ticket Management System for AgroTech Admin

frontend/package-lock.json, frontend/package.json, frontend/src/AgroRentAI/RentProductDetails.jsx, frontend/src/AgroRentAI/components/RatingProductReview.jsx
Reviews on the Product Details page.
This Pr adds the complete ratings/review model for the services with the following features
Rating System:
Display average rating of the product based on user reviews (1-5 stars).
Allow users to submit their ratings when reviewing.
Display individual ratings (e.g., 1 star, 2 stars, etc.) with an overall average rating.
Comment Submission:
Text area for Reviews:
Allow customers to submit their review comments with an optional title for the review.
Review List:
Display Reviews:
Show existing reviews with user names, rating (stars), and comment text.
Show the date when the review was submitted.
Graphical Representation:
Rating Distribution Graph:
Display a bar chart or pie chart showing how many people rated the product with each score (1-5 stars). …
=> Add ratings/reviews on the product details page

backend/controllers/rent/ReviewControllers.js, backend/index.js, backend/model/rent/rentProduct.js, backend/model/user.js, backend/package-lock.json, backend/package.json, backend/routes/rent/reviewRoutes.js
Compelete Backend Implementation for review/rating models
This apps add implemetations for the following fields
// Submit a review
router.post("/products/:productId/reviews");
// Get reviews for a product
router.get("/products/:productId/reviews", getReviews);
// Get rating distribution for a product
router.get("/products/:productId/rating-distribution", getRatingDistribution);
Modified user and rentProudcts schemas to match the prupose
Implemented Advanced APIs for real time ratings calculations and fetching.
Added express-validator for validations of reviews 
Implemented rigorous error logging via winston logger.
=> Add Advanced reviews/rating APIs

backend/controllers/shop/sub-controllers/agentController.js, backend/middleware/sub-ware/agentMiddleware.js, backend/model/shop/sub-model/Agent.js, backend/routes/sub-routes/agentRoutes.js
This PR introduces an agent management system that includes:
- **Agent Schema**: Defines the structure of agents in the database with fields such as name, email, role, and assigned tickets.
- **Agent Controller**: Implements CRUD operations (create, update, retrieve, delete) for agents, including logic for assigning/unassigning tickets.
- **Agent Middleware**: Ensures agents' existence, validates permissions, and prevents invalid actions (e.g., assigning tickets to inactive agents).
- **Agent Routes**: Adds necessary API routes to manage agents, assign/unassign tickets, and change agent status.
1. **Agent Schema** (`models/Agent.js`):
- Defined a schema for the agent, with necessary fields like name, email, assigned tickets, and status.
- Added validations for the agent's email and …
=> Implement Agent Management System with CRUD Operations, Ticket Assignment, and Role-based Access Control

frontend/src/AgroShopAI/components/Pages/Admin-Warehouse.jsx, frontend/src/AgroShopAI/components/Pages/DeleteModal.jsx, frontend/src/AgroShopAI/components/Pages/EditModal.jsx, frontend/src/AgroShopAI/components/Pages/WareInventoryTable.jsx, frontend/src/AgroShopAI/components/Pages/WareSearchAndFilter.jsx, frontend/src/MainContent.jsx
**Add Warehouse Inventory Page with Search, Filter, Edit, Delete, and Upload Functionality**
This PR introduces the `WarehouseInventory` page along with its related components, providing a complete inventory management system. The new page includes functionality for:
- **Search and Filtering**: Users can search inventory items by name and filter them by category.
- **Inventory Table**: Displays a sortable inventory list with options for item selection, editing, and deletion.
- **Edit Modal**: Allows users to edit individual inventory items.
- **Delete Modal**: Provides a confirmation dialog for deleting single or multiple items.
- **Upload Modal**: Enables bulk upload of inventory items via file input.
1. **Added Components**:
- `SearchAndFilter`: Handles search and filter inputs.
- …
=> Added Warehouse Inventory Page with Search, Filter, Edit, Delete, and Upload Functionality

frontend/src/AgroShopAI/components/Pages/Admin-Dashboard.jsx, frontend/src/AgroShopAI/components/Pages/components/ActiveSessions.jsx, frontend/src/AgroShopAI/components/Pages/components/ActivityLog.jsx, frontend/src/AgroShopAI/components/Pages/components/Message.jsx, frontend/src/AgroShopAI/components/Pages/components/Notifications.jsx, frontend/src/AgroShopAI/components/Pages/components/PasswordForm.jsx, frontend/src/AgroShopAI/components/Pages/components/PersonalInfo.jsx, frontend/src/AgroShopAI/components/Pages/components/ProfileManage.jsx, frontend/src/AgroShopAI/components/Pages/components/SecuritySettings.jsx, frontend/src/AgroShopAI/components/Pages/components/TabNav.jsx
This pull request introduces the `ProfileEdit` page along with its associated components for a more modular and maintainable codebase. The Profile Edit page is divided into smaller, reusable components, each handling a specific section of the profile settings.
1. **Main ProfileEdit Component:**
- The main component holds the overall layout and state management for the profile edit page.
- Introduced tab navigation to switch between different profile sections (Personal Info, Password, Notifications, Security, Activity Log, Active Sessions).
2. **Tab Navigation Component (TabNav):**
- A reusable navigation component to allow users to switch between tabs (Personal Info, Password, Notifications, etc.).
- Active tab is dynamically managed via state.
3. **PersonalInfo Component:**
- Handles the …
=> Create Profile Edit Page (Admin)  with Separated Components

backend/controllers/shop/sub-controllers/deliveryPersonController.js, backend/middleware/sub-ware/validate.js, backend/model/shop/sub-model/DeliveryPerson.js, backend/services/sub-service/hashPassword.js
**Overview:**
This PR adds a backend solution for managing delivery personnel within the system, implementing features such as CRUD operations, status toggling, and consistent response handling. This functionality allows for seamless management of delivery personnel with validation, secure password handling, and error messaging.
---
- closes #977 
- **Schema Design:** The `DeliveryPerson` schema includes fields such as `name`, `email`, `phone_number`, `status`, `assigned_routes`, `vehicle_details`, `profile_picture`, and `password`. 
- **Field Validations:** Email and phone number are validated for uniqueness and format correctness.
- **Password Security:** Passwords are hashed using a utility function, ensuring stored passwords are secure.
- **Create Delivery Person:** Adds new personnel …
=> Backend Implementation for Delivery Person Management

backend/controllers/rent/RewardsController.js, backend/index.js, backend/middleware/rent/loyaltyMiddleware.js, backend/model/rent/reward.js, backend/model/user.js, backend/routes/rent/rewardsRoutes.js
Loyalty Program and Rewards APIs
Points and Rewards System: Design a system to accumulate points per rental, redeemable for discounts or perks.
Referral Tracking and Rewarding: Enable referral tracking for rewarding users who bring new customers.
Loyalty and Tiered Discounts: Provide loyalty-based pricing tiers and discounts for repeat customers.
// 1. Accumulate Points on Rental
router.post("/rentals/:rentalId/complete", accumulatePoints);
// 2. Redeem Points for Rewards
router.post("/redeem", redeem);
// 3. Referral Tracking and Points Award
router.post("/referral", referral);
// 4. Get User Points and Rewards
router.get("/points-rewards", pointRewards );
//5.Loaylty Middleware for users creating the rentals.
=> Add Loyalty and rewards APIs

frontend/src/AgroShopAI/components/Pages/FeaturedProductsSection.jsx, frontend/src/AgroShopAI/components/Pages/HeroSection.jsx, frontend/src/AgroShopAI/components/Pages/NotficationHeader.jsx, frontend/src/AgroShopAI/components/Pages/NotificationPage.jsx, frontend/src/MainContent.jsx
This PR introduces a new notification system for the notices section of the Agroshop website. The notification component is triggered when a new notice is added by the admin, providing feedback to the user. This feature includes the following components:
1. **Notification Component**: A reusable component that displays a notification at the top-right of the screen when a new notice is added.
2. **Notices Section**: Updated to include functionality for adding new notices and triggering notifications. The section includes both admin and user views.
3. **App Component**: Updated to manage the notification state and render the `Notification` component conditionally.
- **Notification Component** (`Notification.js`):
- Displays a notification at the top-right of the page when a new notice is …
=> Add Notification Page for Notices in agrotech

backend/controllers/shop/sub-controllers/damagecontroller.js, backend/model/shop/sub-model/damagemodal.js, backend/routes/sub-routes/routesdamage
This pull request introduces the backend logic for managing malfunctioning products in the system. The key features include:
- **Schema Definition**: Created a new schema for `MalfunctioningProduct` that links to a `Product` and stores details about the malfunction, actions taken, and the user responsible.
- **Controller Logic**: Added robust CRUD operations (Create, Read, Update, Delete) for malfunctioning products.
- `createMalfunctioningProduct`: Handles product creation with validation.
- `getMalfunctioningProduct`: Fetches a specific malfunctioning product by ID.
- `updateMalfunctioningProduct`: Updates existing malfunctioning product data.
- `deleteMalfunctioningProduct`: Deletes a malfunctioning product.
- `getAllMalfunctioningProducts`: Supports pagination and search …
=> Add Backend Support for Managing Malfunctioning Products with Enhanced Validation and Error Handling
