frontend/src/App.jsx
frontend/src/MainContent.jsx
frontend/src/components/Footer.jsx
frontend/src/components/UseScrollToTop.jsx

GO TO TO WHEN CLICK IN FOOTER
fixes: #18

issue19_goto

---

frontend/src/components/weather/WeatherCard.jsx
frontend/src/context/StateContextProvider.jsx
frontend/src/pages/Forecast.jsx

fixed StateContextProvider.jsx

---

frontend/src/components/TestimonialSlider.jsx

Enhancement: Hover Effects on Testimonial Slider
This PR introduces hover effects to the Testimonial Slider component. The key updates include:
Button Hover Effect:
The Next and Previous buttons now scale up with a smooth transition (hover:scale-125), providing a more interactive and engaging user experience.
Testimonial Card Hover Effect:
Each testimonial card scales up slightly when hovered (hover:scale-110), creating a visually appealing highlight effect for individual testimonials. This enhances the overall user interaction with the slider.
Consider this under hacktoberfest2024 , hacktoberfest-accepted, GSSOC-ext.
Footer

feat : Added Hover Effect to the Testimonial Part

---

frontend/src/pages/Forecast.jsx

Added responsiveness to the Forecast Page 
Made the page responsive in all interfaces
Fixes #70 
https://github.com/user-attachments/assets/93fc8144-ca8b-42fd-94df-15574914443c
Footer

fixed Forecast.jsx

---

frontend/package-lock.json
frontend/package.json
frontend/src/context/StateContextProvider.jsx

Added backup API key
AFter the limit is crossed this api key can be used!
Fixes #53 
Check this it works correctly
The Key is commented here in StateContextProvider.jsx:

added backup api key

---

frontend/package-lock.json
frontend/src/components/Disease.jsx
package-lock.json

3D Flip Cards for Fruit Disease Information with MouseEnter/Leave
This PR enhances the existing fruit cards with **3D flip animations**, triggered on hover using `MouseEnter` and `MouseLeave`. The flip reveals disease information for each fruit/vegetable, providing more interactive insights for farmers. State is managed using React's `useState` for individual card control.
Fixes #81 
- Added 3D flip effect on hover using `MouseEnter` and `MouseLeave`.
- Managed state for individual card flips.
- Updated CSS for smooth transitions and depth perspective.
This enhancement improves user experience, making it easier for farmers to access disease information at a glance.
https://github.com/user-attachments/assets/5d7f0ad7-4c6d-4c5a-be67-1c7c2d7d0df6

Enhanced the Disease Cards with the 3-D Flip which looks better and gives more insights

---

frontend/src/components/Footer.jsx

Footer is changed
I have added the hover effects and the animations  
#90 
Please label the Hacktoberfest-accepted and Gssoc-etd

Footer UI is changed

---

frontend/src/components/Footer.jsx

update the Twitter symbol to "X" to reflect Twitter's recent rebranding.
update the Twitter symbol to "X" to reflect Twitter's recent rebranding.
fix #99 issue 
update the Twitter symbol to "X" 
Footer

Update Twitter icon in Footer.jsx

---

frontend/src/components/CropRecommendation.jsx
frontend/src/components/Disease.jsx
frontend/src/components/Fertilizer.jsx
frontend/src/components/SoilQuality.jsx

**Added Hover effect and smooth transition on button**
On the /corpRecommendation component added hover effect and smooth transition on button. improving user experience.
using tailwind css
Added hover effect and smooth transition to button.
Footer

Added Hover effect on Button

---

frontend/src/MainContent.jsx

Reverts manikumarreddyu/AgroTech-AI#118

Revert "Update MainContent.jsx"

---

frontend/src/pages/Home.jsx

Reverts manikumarreddyu/AgroTech-AI#117

Revert "Update Home.jsx"

---

frontend/src/MainContent.jsx
frontend/src/components/CropRecommendation.jsx
frontend/src/components/Disease.jsx
frontend/src/components/Fertilizer.jsx
frontend/src/components/Footer.jsx
frontend/src/components/Prices.jsx
frontend/src/components/SoilQuality.jsx
frontend/src/pages/About.jsx
frontend/src/pages/Contact.jsx

added contact us page

---

frontend/src/components/Footer.jsx

added rate us option

---

README.md

Improvements to README.md and visual enhancements
#125
improved README file

Added improvements to README.md and visual enhancements

---

frontend/src/components/Footer.jsx

Made the required changes to Rate us section.
This resolves issue #131. Made the text visible, changed the dialob box size, centered the text, and changed the font.
Fixes #131

Rate-us section changes

---

frontend/src/components/Navbar.jsx
frontend/src/components/Prices.jsx
frontend/src/components/Reports.jsx

Fix Navbar distortion caused by the addition of "Irrigation system" item
This PR addresses the issue where the navbar layout became distorted after adding a new item labeled "Irrigation system." The issue was due to insufficient space and CSS conflicts that caused the navbar to overflow and misalign. Adjustments have been made to ensure the navbar maintains its proper alignment and responsiveness, accommodating the new item without breaking the layout.
#171
Adjusted the CSS for the navbar to accommodate the new "Irrigation system" item.
Not Necessary
Footer

Fix Navbar distortion caused by the addition of "Irrigation system" item

---

frontend/src/pages/Article.jsx

Refactor Article Page Styling to Use Tailwind CSS Instead of External CSS 
We need to refactor the existing styling of the article page by replacing the external CSS with Tailwind CSS for better consistency and maintainability across the project. This change will allow for faster development, reduced CSS file sizes, and more flexibility in design.
Closes: #175 
converted external css of article page into tailwind css

Refactor Article Page Styling to Use Tailwind CSS Instead of External CSS 

---

frontend/src/components/Footer.jsx
frontend/src/components/Navbar.jsx

footer updated

---

crop-rotation-api/app.py
crop-rotation-api/requirements.txt
frontend/src/MainContent.jsx
frontend/src/components/CropRecommendation.jsx
frontend/src/components/CropRotationRecommendation.jsx
frontend/src/components/Navbar.jsx

Added AI-powered Crop Rotation Suggestions
Used Random Forest to create a model with features such as Previous Crop	Soil Type	Moisture Level	Nitrogen (N)	Phosphorus (P)	Potassium (K)
#61
Added Crop rotation recommendation model and create UI for the same

Added AI-powered Crop Rotation Suggestions

---

frontend/src/components/Navbar.jsx

Increase size of the text in navbar when we hover on them
Background color changes when we hover on the navbar text
This PR introduces a hover effect on the navbar text by changing the background color when the user hovers over each navbar item. The purpose of this change is to enhance user interaction and improve the visual appeal of the navigation menu.
Fixes #195
Implemented a background color change for navbar text when hovered, enhancing user interaction.
Introduced a smooth transition effect for the background color change, improving visual appeal.
Footer

Increase size of the text in navbar when we hover on them

---

frontend/src/components/Navbar.jsx

hover effect changed

---

frontend/src/pages/Contact.jsx

Changed the logos in the contact page #143 
Changed the logos in the contact page
Changed the logos in the contact page

Changed the logos in the contact page

---

frontend/src/pages/Contact.jsx

added contact us

---

sugarcane-disease-api/app.py
sugarcane-disease-api/models/Readme.md
sugarcane-disease-api/prediction.py
sugarcane-disease-api/requirements.txt
sugarcane-disease-api/uploaded_image/readme.md

Add Sugarcane Disease Prediction API with Flask
This pull request introduces a new Flask-based API for predicting sugarcane diseases based on uploaded images. The API utilizes an ensemble of machine learning models to classify sugarcane health, providing detailed information about each disease.
Closes : #156 
- Implemented the `/submit_sugarcane` endpoint for image uploads and predictions.
- Created a detailed response structure that includes class labels, descriptions, symptoms, impact, and recommended actions.
- Added error handling for file uploads and predictions.
- Integrated CORS to allow cross-origin requests.
- Added a root endpoint to check the API's operational status.
https://github.com/user-attachments/assets/6fa8a6fb-5ae8-495e-9fcb-b9702ed900ef
The API has been tested with …

Backend API for Sugarcane Disease Prediction Model

---

frontend/src/App.jsx
frontend/src/MainContent.jsx
frontend/src/components/AIEngine.jsx
frontend/src/components/Disease.jsx
frontend/src/components/Submit.jsx

Reverts manikumarreddyu/AgroTech-AI#221

Revert "Add Frontend for Sugarcane Disease Prediction Backend"

---

frontend/src/components/Disease.jsx

Fixed the cards.
Fixed the cards by adding read more and read less buttons with scroll bar. Also added a title at the back. And fixed multiple flipping of cards
fixes #207 
1. Fixed multi flipping of cards.
2. Added a title for cards
3. Added read more and read less buttons with scroll bar.
https://github.com/user-attachments/assets/f52a91bb-f7cc-4643-9e1a-724041c1e4d8
Footer

fixed cards and added readmore button

---

frontend/src/components/Navbar.jsx

Clicking on logo will redirect to hom page
This PR adds functionality to redirect the user to the home page when the logo is clicked. The logo is wrapped in a [Link](vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.esm.html) component from react-router-dom.
Fixex #232 
Wrapped the logo and title in a [Link](vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.esm.html) component.
Added an [onClick](vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.esm.html) handler to close the menu when the logo is …

Enhanced Navbar functionalities with added logo function

---

frontend/src/components/AdvantagesDisadvantages.jsx
frontend/src/components/CropRecommendation.jsx
frontend/src/components/Fertilizer.jsx
frontend/src/components/Irrigation.jsx
frontend/src/components/SoilQuality.jsx

Here's the PR request written in the provided template for adding the Advantages and Disadvantages cards in the Fertilizer, Irrigation, and Soil Quality sections:
---
**Added Advantages and Disadvantages Cards in Fertilizer, Irrigation, and Soil Quality Section**
This pull request adds dynamic cards for displaying advantages and disadvantages in the Fertilizer, Irrigation, and Soil Quality sections of the website. The cards use Tailwind CSS and integrate framer-motion animations for smooth transitions and visual effects. These changes also ensure responsiveness across different screen sizes to improve the user experience.
#229
- Added Advantages and Disadvantages cards to the Fertilizer, Irrigation, and Soil Quality sections.
- Used Tailwind CSS for styling and responsiveness.
- …

Added the Advantages and Disadvantages cards with framer motion and special Effects in the Fertilizer, Irrigation and soil section

---

frontend/src/components/FAQ.jsx

Add hover effect to FAQ
This pull request replaces the click functionality with hover functionality for displaying FAQ answers. When a user hovers over a question, the corresponding answer will be displayed.
Fixes #231 
Updated styles to ensure consistent appearance when hovered.
https://github.com/user-attachments/assets/37582b4e-e8d1-49c0-8fe4-1f8c5a624a77
Footer

Enhanced styling of FAQ

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Irrigation.jsx

irrigation added

---

e-commerce-backend/index.js
e-commerce-backend/package-lock.json
e-commerce-backend/package.json
e-commerce-frontend/package-lock.json
frontend/src/components/FAQ.jsx
frontend/src/components/Features.jsx
frontend/src/components/Showcase.jsx
frontend/src/components/TestimonialSlider.jsx
frontend/src/pages/About.jsx
frontend/src/pages/Home.jsx

Redesigned the FAQs, Features, and Other Components in the Home Page
This pull request introduces a redesigned layout for the FAQs and Features sections, along with other components on the homepage. The aim is to improve user experience, enhance visual appeal, and ensure a more responsive design across various devices.
Fixes #258
- Redesigned the FAQs section for better readability and engagement.
- Updated the Features section with new card designs for improved aesthetics.
- Ensured consistent spacing and padding across all components.
- Improved responsiveness to accommodate different screen sizes.
- Added hover effects to buttons and cards for enhanced interactivity.
The redesign aims to create a more cohesive and user-friendly experience. Feedback on the new design and any further …

Redesigned the FAQs, Features and other compoenents in the Home Page

---

e-commerce-backend/.env
e-commerce-backend/index.js
e-commerce-backend/middleware/auth.js
e-commerce-backend/model/user.js
e-commerce-backend/package-lock.json
e-commerce-backend/routes/auth.js
frontend/src/App.jsx
package-lock.json
package.json

Setup for Authentication backend
Signin and Signup module that utilizes MongoDB for user authentication and management. 
This feature would include:
- User Registration: Collect and store user data such as username, email, and password (hashed for security) in MongoDB.
- User Login: Authenticate users by validating credentials against stored data.
- Session Management: Use JWT (JSON Web Tokens) to maintain user sessions securely.
- Password Encryption: Implement bcrypt or another secure hashing algorithm to protect passwords.
Fixes #282 
Added folder: Middleware , Models , Routes
Footer

Setup for Authentication backend

---

frontend/src/components/Climate.jsx

changed https

---

frontend/calculators/CropYield.jsx
frontend/calculators/FertilizerRequirement.jsx
frontend/calculators/SoilMoisture.jsx
frontend/calculators/WaterRequirement.jsx

CREATED CALCULATORS PAGE FOR AGRICULUTURE USAGE

---

frontend/src/components/Fertilizer.jsx

Redesign Crop Fertilizer Prediction UI
Redesigned the current crop fertilizer prediction UI to a more advanced dashboard with an intuitive design, improving user experience and accessibility.
#298
- Improved the layout and aesthetics of the fertilizer prediction UI.
- Enhanced user interaction through a more intuitive design.
- Streamlined data visualization for better insights.
Footer

Redesigned the current crop fertilizer prediction UI to a better level dashboard and intutive design

---

frontend/calculators/CropYield.jsx

#275 solved

---

frontend/src/MainContent.jsx
frontend/src/NotFound.jsx

DONE!
Thanks @manikumarreddyu for assigning me this issue.
- Fixed #336 
Hey @manikumarreddyu you can merge this now!
Screenshots:

404 page added

---

frontend/src/components/AdvantagesDisadvantages.jsx
frontend/src/components/SoilQuality.jsx

Enhance Necessity, Map, and Advantages/Disadvantages Section for Soil Quality Prediction
This pull request introduces enhancements to the necessity, map, and advantages/disadvantages sections concerning soil quality prediction. The changes aim to provide a clearer understanding of the importance of soil quality prediction, visualize the relevant data on a map, and present a balanced view of its benefits and drawbacks.
Fixes #337
- Improved the **Necessity Section** to better articulate the importance of soil quality prediction for sustainable agriculture.
- Integrated a **Map** feature that visualizes soil testing center locations, enhancing user engagement and accessibility to relevant data.
- Developed the **Advantages and Disadvantages Section**, providing users with a clear …

Enhanced the necessity, map and the advanatages and disadvantages section with soil quality prediction

---

Eco-Crop Manager

Here the user first should select the they want to know about fruits or vegetables.Then they should select what type of fruits or vegetables they want,then they should click on learn about this crop it shows deatils of the crop which is useful them.
Eco-Crop Manager
Here the user first should select the they want to know about fruits or vegetables.Then they should select what type of fruits or vegetables they want,then they should click on learn about this crop it shows deatils of the crop which is useful them.
Fixes #294
Footer

Create Eco-Crop Manager

---

backend/routes/auth.js
frontend/package-lock.json
frontend/package.json
frontend/src/MainContent.jsx
frontend/src/components/AuthPage.jsx
frontend/src/components/LoginPage.jsx
frontend/src/components/Navbar.jsx
frontend/src/components/SignUpPage.jsx
frontend/src/context/AuthContext.jsx

Added logout functionality and authentication context
Added logout functionality and authentication context
#314
Added logout functionality and authentication context

Added logout functionality and authentication context

---

frontend/src/components/CropRotationRecommendation.jsx

Enhanced the UI for crop rotation recommendation page and added a simplistic design
This pull request enhances the user interface for the crop rotation recommendation page by introducing a more user-friendly and simplistic design. The new design improves the visual layout and usability for users while maintaining functionality.
#300
- Enhanced the UI for the crop rotation recommendation page
- Implemented a simplistic design for improved user experience
No additional information.

Enhanced the UI for crop rotation recommendation page and added a simplistic design

---

Crop Management Guide

It gives the detail information about the procedure.What is the correct time to do.
Crop Management Guide
Gives the detail infomation what procedure should be done.
Fixes #341
Footer

Create Crop Management Guide

---

frontend/src/components/AuthPage.jsx
frontend/src/components/LoginPage.jsx
frontend/src/components/SignUpPage.jsx

done with deployment

---

frontend/src/components/Navbar.jsx

darkmode hide

---

frontend/src/components/Navbar.jsx

Added automatic dropdown list on mouse hover in navbar.

Solved issue#295

---

frontend/src/components/Navbar.jsx

Reverts manikumarreddyu/AgroTech-AI#369

Revert "Solved issue#295"

---

frontend/package-lock.json
frontend/src/components/Fertilizer.jsx
frontend/src/pages/ChatBot.jsx

Revamped Chatbot Interface with Modern Design for Improved User Experience
This PR updates the chatbot's UI, enhancing its appearance with a modern and visually appealing design to improve overall user experience and engagement.
#302
- Redesigned the chatbot interface for a modern and sleek look.
- Enhanced user experience with improved visual elements and usability.
- Ensured the design is responsive and consistent across different devices.
The new design focuses on improving user interaction and enhancing the chatbot’s overall aesthetics.
Footer

Revamped the chatbot interface with a modern, visually appealing design for an improved user experience.

---

frontend/src/components/Fertilizer.jsx

#350
- Fixed text color in dark mode by applying `text-black` class to ensure readability.

Fixed the Text in the dark mode properly by providing text-black

---

frontend/src/MainContent.jsx
frontend/src/components/Footer.jsx
frontend/src/components/TermsAndConditions.jsx

Add Terms and Conditions Page
This pull request introduces a new Terms and Conditions page to the application. The page outlines the rules, guidelines, and legal agreements users must agree to in order to use the website or its services. It provides clarity on user responsibilities and the limitations of liability.
#379
- Added a new Terms and Conditions page to the application.
- Updated the footer to include a link to the Terms and Conditions page for easy access.

Added the Terms and Conditions page

---

frontend/src/MainContent.jsx
frontend/src/components/CookiePolicy.jsx

Add Cookie Policy Page
This pull request introduces a new Cookie Policy page to the application. The page informs users about the use of cookies, detailing what data is collected, how it is utilized, and how users can manage their cookie preferences. This addition enhances transparency and complies with privacy regulations.
#378
- Added a new Cookie Policy page to the application.
- Updated the footer to include a link to the Cookie Policy page for easy access.

Added the cookie policy page

---

e-commerce-backend/package-lock.json
e-commerce-backend/package.json
e-commerce-frontend/package-lock.json
e-commerce-frontend/src/page/Home.js

Improve UI and Rearrange Layout of Home Page
This pull request focuses on enhancing the user interface of the home page by rearranging various components for better spacing and readability. The changes aim to create a more visually appealing layout that improves the overall user experience.
- Improved spacing and alignment of the hero section and product categories.
- Reorganized feature points with icons for better readability.
- Enhanced the layout structure using grid and flexbox utilities for a cleaner design.
- Added responsive design adjustments for various screen sizes.
Footer

Improved E-commerce UI

---

frontend/src/App.css
frontend/src/components/Footer.jsx

Reverts manikumarreddyu/AgroTech-AI#412

Revert "Node modules deleted."

---

frontend/src/pages/Home.jsx

Animation added to elements of Home page
- Implemented animations for various elements on the Home page using framer-motion.
- Added distinct fade-in animations for the heading, paragraph, and button in the hero section.
- Animated the "How It Works" section with staggered animations for each step.
- Incorporated animations for the Features, About, Showcase, Testimonial, and FAQ sections, with specific delays for a smoother scrolling experience.
Fixes : #233 
New feature
For ScreenShots 
check PR #324

Animation added to elements : Issue no #233

---

frontend/src/pages/Home.jsx

Reverts manikumarreddyu/AgroTech-AI#419

Revert "Animation added to elements : Issue no #233"

---

soil-testing-labs-api/app.py
soil-testing-labs-api/requirements.txt

Adding Backend API for Soil Testing Labs with Gemini LLM and Plotly Integration
The feature aims to enhance the existing Soil Testing Labs Finder application by integrating Gemini LLm and Plotly to visually display soil testing labs in a specified location on an interactive map. Users can input their location and receive a list of nearby soil testing labs, complete with their names, coordinates, and Google Maps links for navigation. The application will feature an interactive map that marks each lab's location, allowing users to easily identify the proximity and navigate to the labs.
#371
Added Backend API for Soil Testing Labs with Gemini LLM and Plotly Integration
NA

Added Backend API for Soil Testing Labs with Gemini LLM and Plotly Integration

---

e-commerce-frontend/src/App.jsx
e-commerce-frontend/src/component/Footer.jsx

Added footer with green gradient theme to e-commerce frontend
Implemented a minimalist footer with a green gradient theme, including essential sections like About Us, Quick Links, and Contact Us.
Fixed : #399
- Added responsive footer.
- Styled with Tailwind CSS using a green gradient.
N/A

Added the Footer component in the app.jsx

---

e-commerce-frontend/src/page/Home.jsx

Improved Home page UI 
Fixed image carousel.
Fixes: #386

Improved home page UI

---

frontend/sitemap.xml

added sitemap.xml
added sitemap.xml for crawlers

added sitemap.xml

---

frontend/src/pages/AgroRentalAI/HeroSection.Rentjsx

Designed Hero Section for AgroRent AI with Search Buttons and Effects
Created an intuitive Hero section for the AgroRent AI website. Added search buttons and implemented modern effects to enhance user experience.
Fixed : #447
- Designed Hero section layout.
- Integrated search functionality.
- Applied visual effects for an interactive UI.
None.

Designed the Hero Section page for AgroRent AI with search buttons and proper effects

---

frontend/src/components/LoginPage.jsx
frontend/src/components/SignUpPage.jsx

urls changed

---

frontend/src/pages/Home.jsx

Resolved bug in chatbot authentication
Resolved bug in chatbot authentication
#470
Resolved bug in chatbot authentication
.
.

Resolved bug in chatbot authentication

---

frontend/src/MainContent.jsx
frontend/src/components/Navbar.jsx
frontend/src/components/NewsCard.jsx
frontend/src/components/NewsForum.jsx

Added Agriculture News Forum
This feature involves creating a dedicated news forum within the platform that focuses exclusively on agriculture-related news. The forum will aggregate the latest developments, innovations, policies, and market trends relevant to the agriculture industry. It will offer a space for users—farmers, agricultural experts, policymakers, and other stakeholders—to stay informed about current events affecting the agricultural sector. The news will be regularly updated from trusted sources, covering topics such as new farming techniques, climate change impact, government policies, crop market prices, and technological advancements.
#315
Added Agriculture News Forum with News API and selective search functionality

Added Agriculture News Forum

---

electrical-electronics-shops-api/app.py
electrical-electronics-shops-api/requirements.txt

Added electrical and electronics shops finder backend
The feature aims to create the backend of Electrical and Electronics Shops Finder application by integrating Gemini LLm and Plotly to visually display soil testing labs in a specified location on an interactive map. Users can input their location and receive a list of nearby Electrical and Electronics Shops, complete with their names, coordinates, and Google Maps links for navigation. The application will feature an interactive map that marks each location, allowing users to easily identify the proximity and navigate to the labs.
Resolves #478 
Added electrical and electronics shops finder backend
.
.

Added electrical and electronics shops finder backend

---

electrical-electronics-shops-api/app.py
electrical-electronics-shops-api/requirements.txt
frontend/src/MainContent.jsx
frontend/src/components/ElectricalElectronicsShops.jsx
frontend/src/components/Navbar.jsx
frontend/src/styles/ElectricalElectronicsShops.css

Created frontend for Electrical and Electronics Shops and Integrations
The feature aims to create the UI part and integration of Electrical and Electronics Shops Finder application with Mapbox by integrating Gemini LLm and Plotly to visually display soil testing labs in a specified location on an interactive map. Users can input their location and receive a list of nearby Electrical and Electronics Shops, complete with their names, coordinates, and Google Maps links for navigation. The application will feature an interactive map that marks each location, allowing users to easily identify the proximity and navigate to the labs.
#479
Created frontend for Electrical and Electronics Shops and Integrations
.

Created frontend for Electrical and Electronics Shops and Integrations

---

README.md

Deleted previous website images

---

CONTRIBUTING.md

Enhancement In The Documentation 
Done some enhancements which provides more clarity and precise information. Also added some new sections.
"Fixes #512 "
1) Added a project structure section 
2) Added Steps to Contribute Using the Command Line
3) Added Need Help section
4) Also swapped the positions of issues report process and pull request process
5) Done some small enhancements also (alignment and structure) 
If any changes is required please kindly let me know
Footer

Done Some Enhancements And Also Added Some New Sections

---

frontend/src/components/tools/FertilizerRequirement.jsx
frontend/src/index.css

#509 
A simple UI changes for the overall experience
There was a margin error which I have solved .
Because of the margin issue there was slight Ui delay experience 
Footer

Margin added to the Tool section of Fertilizer requirement section

---

agro-quiz-app/src/lib/ai.ts

Removed API key
Removed API key->
#525 
Removed API key
.
.

Removed API key

---

frontend/src/components/AboutUs.jsx

_#Issue No : #480_
Added Responsiveness in About Us Page
Changed the aboutus page for Mobile View
Customization of About Us page

Added Responsiveness

---

frontend/src/AgroShopAI/HomeShop.jsx
frontend/src/AgroShopAI/components/CardContainer.jsx
frontend/src/AgroShopAI/components/CardRelay.jsx
frontend/src/AgroShopAI/components/Categories.jsx
frontend/src/AgroShopAI/components/HeroSectionShop.jsx
frontend/src/AgroShopAI/components/LargeCardContainer.jsx
frontend/src/AgroShopAI/utils/home-data.js

This PR introduces several new categories to improve the user experience on the homepage of the application. The following categories have been added:
- **Organic Farming**
- **Today's Offers**
- **Top Fertilizers**
- **Top Seeds**
- **Best Selling Items**
In addition to the new categories, I have enhanced the aesthetic of the homepage by incorporating multiple banners. These changes are aimed at providing a more visually appealing and informative experience for users.
- **New Categories**:
- Added the following categories to the homepage:
- Organic Farming
- Today's Offers
- Top Fertilizers
- Top Seeds
- **Aesthetic Improvements**:
- Introduced multiple banners on the homepage to make it visually appealing.
- Adjusted layout and spacing for better readability and navigation. …

Added More Categories and Enhanced Homepage Aesthetics

---

frontend/src/AgroShopAI/components/LargeCardContainer.jsx
frontend/src/AgroShopAI/components/ShopFooter.jsx
frontend/src/MainContent.jsx

This pull request introduces a new footer component to the AgroShop e-commerce platform. The footer includes important sections like "About," "Mail Us," "Group Companies," "Help," and "Consumer Policy." It also incorporates social media icons for enhanced user engagement.
---
1. **Footer Structure:**
- Divided the footer into multiple columns for better organization and readability.
- Added the "About" and "Office Address" sections in one column.
- Added a "Mail Us" column with company address and email.
- Grouped links to group companies (AgroRent and AgroTechAI).
- Provided a "Help" section with links to various customer support topics.
- Included a "Consumer Policy" section outlining key policies.
2. **Social Media Integration:**
- Added social media icons (Facebook, …

Added Footer to AgroShop

---

frontend/src/components/ElectricalElectronicsShops.jsx
frontend/src/components/SoilTestingCenters.jsx
frontend/src/styles/ElectricalElectronicsShops.css
frontend/src/styles/SoilTestingCenters.css

Improved stylings for soil testing and electrical electronics shops
Improved stylings for soil testing and electrical electronics shops
#436
Improved stylings for soil testing and electrical electronics shops

Improved stylings for soil testing and electrical electronics shops

---

frontend/src/components/Navbar.jsx

Reverts manikumarreddyu/AgroTech-AI#533

Revert "added hovereffect at dropdown navlink for desktop"

---

backend/.env.sample
backend/controllers/brandController.js
backend/controllers/categoryController.js
backend/controllers/productController.js
backend/controllers/reviewController.js
backend/controllers/sellerController.js
backend/controllers/variantController.js
backend/index.js
backend/package-lock.json
backend/package.json
backend/routes/shop.js
backend/test/api.test.js

This PR introduces new APIs to the AgroShop application for product management and enhances existing features. The following endpoints have been added:
1. **Product Routes**
- `GET /api/products` - Retrieve a list of all products.
- `GET /api/products/:id` - Retrieve a specific product by ID.
- `POST /api/products` - Create a new product.
- `PUT /api/products/:id` - Update an existing product by ID.
- `DELETE /api/products/:id` - Delete a product by ID.
2. **Category Routes**
- `GET /api/categories` - Retrieve a list of all categories.
- `GET /api/categories/:id` - Retrieve a specific category by ID.
- `POST /api/categories` - Create a new category.
- `PUT /api/categories/:id` - Update an existing category by ID.
- `DELETE /api/categories/:id` - Delete a category by ID.
3. **Review …

Added APIs to handle product data

---

frontend/src/AgroShopAI/components/BottomCardContainer.jsx
frontend/src/AgroShopAI/components/CardRelay.jsx
frontend/src/AgroShopAI/components/DisplayCard.jsx
frontend/src/AgroShopAI/components/Filter.jsx
frontend/src/AgroShopAI/components/ProductCard.jsx
frontend/src/AgroShopAI/pages/CategoryPage.jsx
frontend/src/AgroShopAI/pages/HomeShop.jsx
frontend/src/MainContent.jsx

This PR introduces a new frontend page dedicated to displaying categories of products for the AgroShop application. The page enhances user navigation and improves the overall shopping experience by organizing products into visually appealing categories.
**Changes Made:**
- **Category Page Layout:**
- Implemented a responsive layout using Tailwind CSS, ensuring compatibility across various screen sizes.
- Added product images, titles, prices, and a “Buy Now” button for each product card.
- **Filtering Options:**
- Integrated a filtering component that allows users to filter products based on specific criteria (e.g., type, price range).
- **Dynamic Product Display:**
- Developed a dynamic product display system that updates the visible products based on selected filters.
- …

Frontend Page for Product Categories

---

backend/controllers/categoryController.js
backend/controllers/productController.js
backend/index.js
backend/package.json
backend/routes/shop.js
backend/test/api.test.js

This PR introduces the implementation of Product and Category APIs for the AgroShop e-commerce application. These APIs will enable CRUD operations for managing products and categories, enhancing the overall functionality of the application.
- **Product API**:
- **GET /api/products**: Retrieve a list of all products.
- **POST /api/products**: Create a new product.
- **GET /api/products/:id**: Retrieve details of a specific product.
- **PUT /api/products/:id**: Update an existing product.
- **DELETE /api/products/:id**: Delete a product by ID.
- **Category API**:
- **GET /api/categories**: Retrieve a list of all categories.
- **POST /api/categories**: Create a new category.
- **GET /api/categories/:id**: Retrieve details of a specific category.
- **PUT /api/categories/:id**: Update an …

Added category and product apis for database

---

backend/controllers/brandController.js
backend/controllers/sellerController.js
backend/routes/shop.js
backend/test/api.test.js

This PR introduces new APIs for managing brands and sellers within the application. The added functionality allows users to create, read, update, and delete (CRUD) brand and seller records, enhancing the overall product management capabilities.
**Changes Made:**
1. **Brand API:**
- **GET /api/brands:** Retrieve a list of all brands.
- **GET /api/brands/:id:** Retrieve details of a specific brand by ID.
- **POST /api/brands:** Create a new brand.
- **PUT /api/brands/:id:** Update an existing brand by ID.
- **DELETE /api/brands/:id:** Delete a brand by ID.
2. **Seller API:**
- **GET /api/sellers:** Retrieve a list of all sellers.
- **GET /api/sellers/:id:** Retrieve details of a specific seller by ID.
- **POST /api/sellers:** Create a new seller.
- **PUT /api/sellers/:id:** Update an …

Added Brand and Seller APIs for database

---

agrotech-ai-apis/.gitignore
agrotech-ai-apis/app.py
agrotech-ai-apis/crop_recommendation.py
agrotech-ai-apis/paddy_prediction.py

Integrated crop rotation recommendation api
Integrated crop rotation recommendation api
#579
Integrated crop rotation recommendation api

Integrated crop rotation recommendation api

---

backend/controllers/reviewController.js
backend/controllers/variantController.js
backend/routes/shop.js
backend/test/api.test.js

This PR implements the Review and Variant APIs for the AgroShop e-commerce application. These APIs facilitate the management of product reviews and variations, enhancing product detail capabilities for users.
- **Review API Endpoints**:
- `GET /api/reviews`: Retrieve a list of all reviews.
- `GET /api/reviews/:id`: Retrieve details of a specific review by ID.
- `POST /api/reviews`: Create a new review for a specific product.
- `PUT /api/reviews/:id`: Update an existing review by ID.
- `DELETE /api/reviews/:id`: Delete a review by ID.
- **Variant API Endpoints**:
- `GET /api/variants`: Retrieve a list of all variants.
- `GET /api/variants/:id`: Retrieve details of a specific variant by ID.
- `POST /api/variants`: Create a new variant for a specific product.
- `PUT /api/variants/:id`: …

Added Review and Variant APIs for database

---

agrotech-ai-apis/app.py
agrotech-ai-apis/seed_quality_predictor.py

Added Seed Quality Predictor
Added Seed Quality Predictor
#585
Added Seed Quality Predictor

Added Seed Quality Predictor

---

.github/scripts/update_structure.py
.github/workflows/update-readme.yml
README.md
agrotech-ai-apis/app.py
agrotech-ai-apis/seed_quality_predictor.py
repo_structure.txt

Automated project structure updation using github workflows and action bot
Automated project structure updation using github workflows and action bot
#586
Automated project structure updation using github workflows and action bot

Automated project structure updation using github workflows and action bot

---

backend/controllers/categoryController.js
backend/controllers/productController.js
backend/controllers/sellerController.js
backend/model/shop/product.js
backend/routes/shop.js
frontend/src/AgroShopAI/components/Categories.jsx
frontend/src/AgroShopAI/components/Filter.jsx
frontend/src/AgroShopAI/components/ProductCard.jsx
frontend/src/AgroShopAI/pages/CategoryPage.jsx
frontend/src/AgroShopAI/utils/home-data.js
frontend/src/MainContent.jsx

This PR implements the connection between the frontend and backend for the AgroShop category page, making it dynamic and responsive to user interactions. The following changes were made:
1. **Backend Integration**:
- Established API endpoints to fetch category data from the backend.
- Ensured that the backend serves relevant category details, including images, descriptions, and product lists.
2. **Frontend Enhancements**:
- Updated the AgroShop category page to utilize the newly created API endpoints.
- Implemented state management to handle the fetched data and render it dynamically.
- Added loading indicators to enhance user experience while data is being fetched.
3. **Dynamic Rendering**:
- Implemented a mapping function to display category information based on API responses.
- Ensured …

Connected Frontend and Backend for Dynamic AgroShop Category Page

---

agrotech-ai-chatbot/src/main.py
frontend/src/pages/ChatBot.jsx
package-lock.json

This PR introduces a set of pre-made prompts to the chatbot interface, streamlining user interactions and improving user engagement. These prompts will help guide users in formulating queries and selecting relevant topics for inquiry, simplifying the interaction process.
Fixes #429 
The pre-made prompts enhance user satisfaction by offering clear, relevant examples of queries. Users unfamiliar with the chatbot's capabilities can easily select prompts and navigate through the website for further exploration.

Add Pre-Made Prompts to Chatbot Interface for Improved User Engagement

---

backend/model/shop/extendedUser.js

This pull request extends the existing User schema to accommodate e-commerce functionalities, including user roles, addresses, cart items, wishlist items, order history, and payment methods. This enhancement allows for better management of user data in the context of an online store.
- Closes #595 
- Added role field to differentiate between customers and admins.
- Implemented address schema to store multiple shipping addresses.
- Created cart and wishlist schemas to manage user-selected items.
- Defined order history structure to track past purchases.
- Added payment methods schema for storing user payment preferences.
---

Extend User Schema for E-commerce Features

---

agrotech-ai-apis/app.py
agrotech-ai-apis/plant_disease_detection.py

Integrated crop disease detection api
Integrated crop disease detection api
Fixes #584
Integrated crop disease detection api

Integrated crop disease detection api

---

agrotech-ai-apis/app.py
agrotech-ai-apis/plant_disease_detection.py
frontend/src/MainContent.jsx
frontend/src/components/Navbar.jsx
frontend/src/pages/BestPractices.jsx

Added Best practices page in help section with great UI and framer motion style
Added Best practices page in help section with great UI and framer motion style
Fixes #605
Added Best practices page in help section with great UI and framer motion style

Added Best practices page in help section with great UI and framer motion style

---

agrotech-ai-apis/app.py
agrotech-ai-apis/plant_disease_detection.py
frontend/src/AgroRentAI/HeroSectionRent.jsx
frontend/src/MainContent.jsx
frontend/src/components/Navbar.jsx
frontend/src/pages/BestPractices.jsx

Developed Agro Rent and Lease page with How it works, Features, FAQ, Search Box in a great sleek UI and framer motion
Developed Agro Rent and Lease page with How it works, Features, FAQ, Search Box in a great sleek UI and framer motion
#622
Develop Agro Rent and Lease page with How it works, Features, FAQ, Search Box in a great sleek UI and framer motion
Following this, I would like to work on creating backend schemas for rental and lease products.

Develop Agro Rent and Lease page with How it works, Features, FAQ, Search Box in a great sleek UI and framer motion

---

frontend/src/components/models/Fertilizer.jsx
frontend/src/components/models/SoilQuality.jsx

Improve Client side form validation in Soil & Fertilizer section
Implemented client-side form validation in the Soil and Fertilizer Prediction sections. This ensures that inputs are validated properly before submission, improving user experience and preventing invalid data from being sent to the server.
Fixes #582 
- Added HTML validation attributes for numeric input fields.
- Updated form state management using useState for validation.
- Implemented user-friendly error messages for invalid inputs.
none

Improve Client side form validation in Soil & Fertilizer section

---

backend/.env.sample
backend/index.js
backend/middleware/auth.js
backend/model/user.js
backend/routes/auth.js
backend/routes/users.js
frontend/src/MainContent.jsx
frontend/src/components/LoginPage.jsx
frontend/src/components/Navbar.jsx
frontend/src/components/Profile.jsx
frontend/src/components/SignUpPage.jsx
frontend/src/context/AuthContext.jsx

Implemented role based access control
Implemented role based access control with roles such as admin, farmer, vendor, customer
Fixes #635 
Implemented role based access control with roles such as admin, farmer, vendor, customer
Following this, I would like to work on creating a good profile page for different roles.

Implemented role based access control

---

README.md

Added Table to Display Repository Statistics in README.md
ISSUE #643 
CLOSE #643 
A clear and concise description of what the PR does.
This PR does the following:
- Adds a table to display repository statistics (stars, forks, open issues, open/closed pull requests) in the README.md.
- Uses markdown syntax with badges/icons to enhance the display.
- Includes dynamic links to sections of the repository for easier access.
Changes
List the detailed changes made in this PR.
- Added a table in README.md to display real-time repository statistics.
- Integrated badges/icons for stars, forks, issues, and pull requests.
- Refactored README.md to include dynamic links to the corresponding sections of the repository.
- [X ] I have tested the changes locally
- [ X] Documentation has been updated (if …

Update README.md Added Table to Display Repository Statistics in README.md

---

frontend/src/components/tools/PlantTaskReminder.jsx

@manikumarreddyu 
I have added deletion functionality
Kindly check it out
https://github.com/user-attachments/assets/e5ed3905-8d7e-434f-bcaa-7bf48f72027d

added detele feature

---

backend/controllers/rating.js
backend/index.js
backend/model/rating.js
backend/routes/users.js
frontend/src/components/Footer.jsx

Add rating feedback implementation to the website
made necessary model controllers and route in the backend for the purpose 
Integrated with the frontend to see realtime confirmation for the successfull rating and unauthorized message if the user is not logged in
Footer

Add Ratings API and frontend

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/tools/PlantTaskReminder.jsx

This PR fixes the error in plant tasks page
removed the alerts and added toast notifications and also fixed the error.
changed the logic a bit and added toast notification 
https://github.com/user-attachments/assets/1a5f51e9-681c-4748-baba-b89237c631ce
Footer

fix plant-task error

---

README.md

Add Table of Contents and API Documentation in README file
This pull request adds a comprehensive Table of Contents and API documentation to the README file, enhancing navigation and providing clear information about the project's features.
- Added a Table of Contents section to the README.
- Included detailed API documentation for various predictions (fertilizer, crop, soil quality, yield, mushroom edibility).
No additional information.

ADD table of Content and API Documentation on README file

---

README.md

Enhance and Structure the Contributors Section
This enhancement aims to provide a clearer representation of our contributors and to acknowledge their efforts in a more structured manner.
#670 
- Visual Representation: Incorporate contributor statistics and visuals, such as:
- A contribution graph showcasing the number of contributions from each contributor.
- A dynamic contributor card that updates automatically based on contributions.
- Gratitude Message: Include a well-crafted thank-you message to express appreciation for the contributors. This message should be warm and engaging, helping foster a sense of community.
- Link to Contributor Profiles: Make the contributor images or names clickable, directing users to their GitHub profiles. This will allow others to explore the work of each …

Enhance and Structure the Contributors Section

---

frontend/src/components/tools/TaskReminder.jsx

@manikumarreddyu 
I have added View History and Clear History feature in Irrigation Task Remainders Section
Kindly check it out
If you like it, could you please consider it as level2
Issue no : #663 
https://github.com/user-attachments/assets/8b240ae9-08a9-423a-b8e6-f2b3a9fe3d0e

added history feature

---

frontend/src/components/models/Prices.jsx
package-lock.json

This Pr enhances the UI of crop price prediction page.
Changes are made in the styling of the components
Footer

Fix crop price prediction page

---

frontend/src/components/models/Fertilizer.jsx
frontend/src/components/models/SoilQuality.jsx

Reverts manikumarreddyu/AgroTech-AI#629

Revert "Improve Client side form validation in Soil & Fertilizer section"

---

frontend/src/components/models/Fertilizer.jsx

Reverts manikumarreddyu/AgroTech-AI#628

Revert "Phosphorous level in Fertilizer Page"

---

frontend/package.json
frontend/src/AgroShopAI/components/ProductCard.jsx
frontend/src/AgroShopAI/pages/Cart.jsx
frontend/src/AgroShopAI/pages/ProductPage.jsx
frontend/src/MainContent.jsx

This PR implements the "Add to Cart" page for the AgroShop application, enhancing the user experience by providing an intuitive cart management interface. The page allows users to view items , adjust quantities, remove items, and proceed to checkout smoothly.
1. **Cart Summary**
- Displays all items added to the cart with each item’s quantity and total price.
2. **Quantity Adjustment**
- Users can easily adjust the quantity of each item in their cart, ensuring flexibility before checkout.
3. **Remove Items**
- A remove option for each item in the cart, allowing users to delete unwanted items seamlessly.
4. **Proceed to Checkout**
- Includes a "Proceed to Checkout" button that will directs users to the checkout page, streamlining the purchasing process. …

Added Cart Page frontend to the agroshop.

---

frontend/src/pages/Contact.jsx

@manikumarreddyu 
I have enhanced the contact us page
Kindly check it out
issue no : #699 
https://github.com/user-attachments/assets/80709ba5-3a32-44e2-ad02-c14ba3c98f96

enhanced contact us page

---

backend/.env.sample
backend/controllers/cartController.js
backend/model/shop/extendedUser.js
backend/routes/shop.js
frontend/.env.sample
frontend/package.json
frontend/src/AgroShopAI/components/CartComponents.jsx
frontend/src/AgroShopAI/components/LoginPrompt.jsx
frontend/src/AgroShopAI/components/ProductCard.jsx
frontend/src/AgroShopAI/components/ReviewSection.jsx
frontend/src/AgroShopAI/pages/Cart.jsx
frontend/src/AgroShopAI/pages/CategoryPage.jsx
frontend/src/AgroShopAI/pages/ProductPage.jsx
frontend/src/components/LoginPage.jsx

**Description:**  
This PR integrates backend functionality with the cart page, enabling management of cart items directly from the frontend. The implementation includes API endpoints to add, update, and remove products from the cart, as well as retrieve and clear the cart.
- Closes #703 
**Key Changes:**
1. **API Endpoints and Controllers:**
- **Add Product to Cart:** `/cart/:userId/add`
- **Retrieve User's Cart:** `/cart/:userId`
- **Update Cart Item Quantity:** `/cart/:userId/update`
- **Remove Product from Cart:** `/cart/:userId/remove`
- **Clear User's Cart:** `/cart/:userId/clear`
2. **Cart Schema Updates:**
- Updated the cart schema to align with frontend requirements.
3. **Frontend Integration:**
- Backend integration has been applied on the product, category, and cart pages.
4. …

[FEAT] Integrated Cart Backend with Cart Page, Category Page and Product Page

---

frontend/src/AgroShopAI/components/ShopNavbar.jsx
frontend/src/MainContent.jsx

This PR introduces a responsive Navbar component that improves navigation across the application. The Navbar features links to essential pages and integrates the functionality for fetching and displaying the user's location.
- **Responsive Design**: The Navbar adjusts seamlessly for mobile and desktop views.
- **Error Handling**: Implements error handling for location fetching, providing user-friendly messages.
- **Added `ShopNavbar.jsx`**: This file contains the Navbar component, which includes:
- Links to various sections of the application.
- A state to hold and display the user's location.
- Functions to handle location fetching and error management.
https://github.com/user-attachments/assets/01011f37-fc35-4085-84aa-f32830ae8532
- Closes #721

Added navigation bar for cart , account and order

---

frontend/src/components/Footer.jsx

redesign the rate us form
redesign the rate up form now looks good for agrotech ai
FIXES #714 
IMPROVEMENTS
before -
after--
Footer

redesign the rate us form

---

backend/controllers/wishlistController.js
backend/model/shop/extendedUser.js
backend/routes/shop.js
frontend/src/AgroShopAI/components/ProductCard.jsx
frontend/src/AgroShopAI/components/ShopNavbar.jsx
frontend/src/AgroShopAI/pages/CategoryPage.jsx
frontend/src/AgroShopAI/pages/Wishlist.jsx
frontend/src/MainContent.jsx

This PR introduces the functionality for managing a user's wishlist, including the creation of wishlist pages and backend integration.
- Closes #720 
1. **Backend Routes for Wishlist**:
- Added the following backend routes:
- `POST /wishlist/:userId/add` - Add a new item to the wishlist.
- `DELETE /wishlist/:userId/remove` - Remove an item from the wishlist.
- `GET /wishlist/:userId` - Retrieve all wishlist items for the user.
2. **Wishlist Page Creation**:
- Implemented a dedicated wishlist page that allows users to view their wishlist items.
- Integrated the backend API to fetch and display wishlist data.
3. **Integration with Category Page**:
- Updated the category page to allow users to add items to their wishlist directly from the category view.
- Ensured smooth communication between …

Added Wishlist Pages and Backend Integration

---

frontend/index.html

I added a visitor count 
My work shows number of visitor 
Fixes #674
I added the visitor counter 
Footer
@manikumarreddyu  Please give higher level as other PA are giving

Added the visitor count

---

README.md

Added hacktoberfes and gssoc banners
Added hacktoberfes and gssoc banners
Fixes #724 
added the banners
- [x ] I have tested the changes locally
- [ x] Documentation has been updated (if necessary)
- [ x] Changes are backward-compatible
Footer

Added hacktoberfes and gssoc banners

---

frontend/src/AgroShopAI/components/ShopNavbar.jsx
frontend/src/AgroShopAI/pages/Profile.jsx
frontend/src/MainContent.jsx

This pull request adds a new profile page to the frontend application, allowing users to manage their personal information effectively. The following features have been implemented:
1. **Add Address Option**: Users can add their address directly from the profile page. The interface includes a form to input address details, which is designed to be user-friendly.
2. **Add Payment Method Option**: A section has been added for users to input and save their payment method details. This functionality will help streamline the payment process during checkout.
3. **Edit User Info**: Users can edit their personal information, including name and email. This allows users to keep their profiles up-to-date with minimal effort.
- Closes #728 
- Created a new `ProfilePage` component to serve as the main …

Added Profile Page to the application

---

backend/controllers/shop/brandController.js
backend/controllers/shop/cartController.js
backend/controllers/shop/categoryController.js
backend/controllers/shop/productController.js
backend/controllers/shop/profileController.js
backend/controllers/shop/reviewController.js
backend/controllers/shop/sellerController.js
backend/controllers/shop/variantController.js
backend/controllers/shop/wishlistController.js
backend/model/shop/extendedUser.js
backend/routes/shop.js
frontend/src/AgroShopAI/pages/Profile.jsx

This PR integrates the profile page with the backend by implementing necessary API endpoints, modifying the `ExtendedUser` collection model, and ensuring that the profile page dynamically interacts with the backend.
- Closes #729 
1. **API Endpoints Created**:
- Implemented the following routes in the profile API:
- **POST `/profile`**: Created a new extended user.
- **GET `/profile/:id`**: Retrieved extended user details by ID.
- **GET `/profile`**: Fetched all extended users.
- **PUT `/profile/:id`**: Updated an existing extended user.
- **DELETE `/profile/:id`**: Deleted an extended user.
2. **Modified ExtendedUser Collection Model**:
- Updated the `ExtendedUser` model to accommodate new fields and ensure compatibility with the front-end requirements.
3. **Dynamic Profile Page**:
- …

 [FEAT] Integrated Profile Page with Backend and Created new APIS

---

frontend/src/components/Footer.jsx

i have make the ui of the alert message of rating message popup.
Rating pop up message ui made good looking
#750 
Changes in Footer file
- [X ] I have tested the changes locally
- [X ] Documentation has been updated (if necessary)
- [X ] Changes are backward-compatible
https://github.com/user-attachments/assets/8468f9cd-2229-4979-bffd-dfbddac91ae2

ratingpopup : #750 done

---

frontend/src/components/tools/TaskReminder.jsx

Enhance the Irrigation Task Reminder UI
Enhance the Irrigation Task Reminder UI
Fix #748

Enhance the Irrigation Task Reminder UI | Issue #748

---

frontend/src/AgroShopAI/components/ShopFooter.jsx
frontend/src/AgroShopAI/pages/FooterPages/CancelAndReturn.jsx
frontend/src/MainContent.jsx

This PR introduces a new "Cancellation and Return Policy" page and updates the footer navigation to include a link to this page. The new policy page provides essential information regarding cancellation and return processes for various product categories, ensuring that customers have access to clear and concise guidelines.
**Changes Made:**
1. **Cancellation and Return Policy Page**:
- Created a dedicated page outlining the cancellation and return policies, including details for different product categories.
- Organized content for clarity, with sections covering general cancellation conditions, return eligibility, and specific product guidelines.
2. **Footer Navigation**:
- Updated the footer component to include a link to the newly created "Cancellation and Return Policy" page.
3. …

Add Cancellation and Return Policy Page with Footer Navigation

---

backend/controllers/rent/RentProductController.js
backend/index.js
backend/model/rent/rentProduct.js
backend/routes/rent/rentProductRoutes.js

Crud APIs for renting products
Wrote the backend routes and controllers for products that are available for renting.
Footer

Add rent-products APIs

---

backend/controllers/rent/RentProductController.js
backend/index.js
backend/routes/rent/rentProductRoutes.js
frontend/src/AgroRentAI/NavigateProducts.jsx

Apply filters/categories on the AGRO RENT page
Add the filtering and categories implementation
Wrote the backend controller and modified the frontend Page to manage states for different filters and categories.
https://github.com/user-attachments/assets/808db74b-245b-409d-b2b6-961a78f36a5d

Add categories and filter implementation

---

frontend/src/AgroRentAI/RentUserDashboard.jsx
frontend/src/MainContent.jsx

User Dashboard
Profile Management: Basic profile details, address management, payment methods.
My Rentals: List of active, pending, and past rentals with details like rental duration, cost, status, and cancellation options.
Saved Items/Wishlist: Users can save products they’re interested in renting later.
Review Submissions: Option to review rented equipment after the rental period.
https://github.com/user-attachments/assets/e8a40272-9909-472d-991d-b0c418055418

Add user dashboard

---

frontend/src/AgroShopAI/components/ShopFooter.jsx
frontend/src/AgroShopAI/pages/FooterPages/Privacy.jsx
frontend/src/MainContent.jsx

This PR implements the **Privacy Policy** page for the platform, providing a dedicated section detailing how user data is collected, used, and protected. The page will be accessible through a link in the footer of every page.
**Changes:**
1. **Privacy Policy Page:**
- A new **Privacy Policy** page has been added.
- The content includes sections such as:
- Introduction
- Information We Collect
- Use of Information
- Data Security
- Your Choices and Rights
- Contact Information
- Changes to Privacy Policy
- Legal compliance information
- The page is styled to match the existing design and is fully responsive.
2. **Footer Link:**
- A new **Privacy Policy** link has been added to the footer of the website.
- The link directs users to the new **Privacy Policy** page.
- It has been ensured that …

Added Privacy policy page

---

frontend/src/MainContent.jsx
frontend/src/components/Footer.jsx
frontend/src/components/Licensing.jsx

fix #810 
Added Fully Responsive and Dedicated Licensing Page
I have implemented the complete and fully responsive Licensing Page that present the website license to the user.
- Ensured responsive UI.
- Ensured better UX.
https://github.com/user-attachments/assets/c7af546c-b7fb-45a6-b14b-50e23e0a5c00

Added Fully Responsive and Dedicated Licensing Page | Issue #810

---

frontend/src/MainContent.jsx
frontend/src/components/CodeOfConduct.jsx
frontend/src/components/Footer.jsx

fix #809 
Added Fully Responsive and Dedicated COC Page
I have implemented the complete and fully responsive COC Page that present the website Code of Conduct to the user.
- Ensured responsive UI.
- Ensured better UX.
https://github.com/user-attachments/assets/0e44f0a3-bf72-463a-802c-9bcf76dce6ca

Added Fully Responsive and Dedicated Code of Conduct Page | Issue #809

---

backend/controllers/shop/utilityController.js
backend/routes/shop.js
frontend/src/AgroShopAI/components/CategoriesBanner.jsx
frontend/src/AgroShopAI/components/sub-components/SearchBar.jsx
frontend/src/AgroShopAI/pages/SearchResult.jsx
frontend/src/MainContent.jsx

This PR introduces product search capabilities to the application. It includes:
1. **Backend API** to handle search requests (`/api/searchproduct?q=`).
2. **Search Results Page** on the frontend to display the products based on search queries.
- Closes #798 
- **Backend API**: Added a new endpoint `GET /api/searchproduct?q=<query>` to handle product search requests.
- Supports case-insensitive and partial matches on both product `name` and `description`.
- Returns an array of matching products
- **Frontend Search Results Page**:
- Created a new component to display search results.
- Integrated with the backend API to fetch and render products based on the search query.
- Added a "No Results Found" message for empty search results.
1. **Backend**:
- `controllers/productController.js`: …

Add Product Search Functionality and Result Page

---

backend/package-lock.json
frontend/src/AgroRentAI/RentCheckoutPage.jsx
frontend/src/MainContent.jsx

Checkout Page for renting Products 
This PR adds the checkout page for renting products so that the user filling in the details receive a message of approval.
https://github.com/user-attachments/assets/9f3631a3-0567-43ca-b689-9563b1bb9015

Add Checkout page

---

backend/controllers/authController.js
backend/model/user.js

[FIX] : Signup Schema Error

---

frontend/src/MainContent.jsx
frontend/src/components/Discussions.jsx
frontend/src/pages/Home.jsx

Discussions page and backend Integration
made the discussions page to integrate with the backend to fetch the posts and comments.
Users can comment on existing posts.
Wrote the frontend page maintaining the theme of the website and implemented the backend APIs.
https://github.com/user-attachments/assets/a401b72a-a4eb-4528-b07c-e364c6ef6845

Add discussions page implementation

---

README.md

Table of contents update in readme file
#832

Table of contents update in readme file

---

frontend/src/AgroRentAI/RentAdminDashboard.jsx
frontend/src/components/NewsForum.jsx

Rent Product listings page.
This PR adds a model for admins to create new products.
Validated the input fields for admins to maintain the consistency for products filling out all the necessary fields,
Shows toast notifications for success and error cases.
https://github.com/user-attachments/assets/cd76fc0e-42bb-4d6c-8efc-99fad17d8a6c

Add product listing

---

frontend/src/AgroRentAI/Cart.jsx
frontend/src/MainContent.jsx

Cart page for Renting
Core Cart Features
Cart Overview: Display items with image, name, variant, price, and quantity.
Total Calculation: Real-time subtotal and total cost.
Modify Items: Quantity selector, item removal, and clear cart option.
Save for Later: Option to save items for future purchase.
Price & Promotions
Discount Codes: Promo code input with validation and discount updates.
Auto Discounts: Apply discounts automatically when eligible.
Shipping & Tax Calculation: Estimate shipping and taxes based on location.
Availability & Recommendations
Stock Check: Show availability and alert if items are out of stock.
Product Suggestions: Recommend related products.
Delivery Estimate: Show estimated delivery time.
User-Friendly Navigation & Persistence
Back to Shopping: Easy navigation …

Add rent cart page

---

backend/controllers/rent/RentWishlistController.js
backend/index.js
backend/model/user.js
backend/routes/rent/rentWishlistRoutes.js
frontend/src/AgroRentAI/NavigateProducts.jsx

Implement the backend and frontend for users to save and wishlists the products so that they are available on the user dashboard.
This PR adds the wishlists backend APIs to associate with the users in the database.
with route for adding , deleting and fetching the wishlists products,
Integrated toggle heart button with the product cards in the frontend to add and delete the products to and from wishlists.
toast for success and failure notifications.
https://github.com/user-attachments/assets/e8a7834a-8f16-4054-a187-89cfb34b68e8

Add Wishlist Implementation

---

frontend/src/components/Navbar.jsx

Remove arrow icon from navbar links
#830

Remove arrow icon from navbar links

---

backend/controllers/authController.js
backend/model/user.js
backend/routes/auth.js
backend/services/emailUtils.js
frontend/.env.sample
frontend/src/components/EmailVerification.jsx
frontend/src/components/SignUpPage.jsx

This PR introduces three new features to the backend for improving user account management:
1. **Email Verification Using Token**
2. **Username Availability Validation**
3. **Email Existence Validation**
1. **Email Verification**  
After signing up, users will receive a verification email with a token. This verification step must be completed before the account is fully activated.
- **Endpoint**: `GET /verify-account`
2. **Username Validation**  
This feature checks if a username is available before completing the signup process, providing feedback to the user if the chosen username is already taken.
- **Endpoint**: `GET /check-username/:username`
3. **Email Validation**  
During signup, this check ensures that the provided email is not already associated with an existing account, helping …

Add Account Verification, Username, and Email Validation

---

backend/controllers/rent/RentCartController.js
backend/index.js
backend/model/user.js
backend/package-lock.json
backend/routes/rent/rentCartRoutes.js
frontend/src/AgroRentAI/Cart.jsx
frontend/src/AgroRentAI/RentProductDetails.jsx

Add to Cart Implementation
Wrote the backend APIs an routes for handling cart functionalities such as Adding, deleting and fetching the cart items.
Integrated the backend API on the rentProductDetails page and RentCart page.
Modified the UI of the cart page to show proper message when no items are added and navigation to the main NavigateProduct page.
Proper toast notifications for cart related functionalies on RentProductDetails and RentCartPage.
https://github.com/user-attachments/assets/1cb9efca-2b3e-4831-966e-598de4e9b4a3

Add to cart Implementaions

---

backend/package-lock.json
frontend/src/AgroRentAI/RentUserDashboard.jsx
frontend/src/AgroRentAI/components/AccountInformation.jsx
frontend/src/AgroRentAI/components/Avatar.jsx
frontend/src/AgroRentAI/components/PaymentMethods.jsx
frontend/src/AgroRentAI/components/ReatalHistory.jsx
frontend/src/AgroRentAI/components/RentNotifications.jsx
frontend/src/AgroRentAI/components/Wishlist.jsx
frontend/src/MainContent.jsx

User Profile Page
Account Information: Edit personal details, upload profile picture, and manage account settings.
Rental History: View current and past rentals with details like rental dates, costs, and feedback.
Payment Methods & Billing: Manage payment options, billing info, and view payment history.
Saved Items & Wishlist: Add items to the wishlist for future rentals.
Notifications & Alerts: Get reminders for rentals, deliveries, discounts, and offers.
Separated the components from the profile page and improvised navigations from the sidebar.
Forms and components for editing profile informations and payment informations.
https://github.com/user-attachments/assets/aa7de1ab-3f18-45a0-9fbf-5b05a3e853a0

Update profile page

---

backend/controllers/authController.js
backend/controllers/userController.js
backend/index.js
backend/model/user.js
backend/package.json
backend/routes/auth.js
frontend/src/MainContent.jsx
frontend/src/components/LoginPage.jsx
frontend/src/components/ResendVerification.jsx
frontend/src/components/SignUpPage.jsx

- Closes #845 
This PR introduces multiple enhancements to the user authentication and verification flow:
1. **Resend Verification Email on Signup**:
- Added the functionality to resend the verification email if the user has not verified their email after signing up. A button has been added on the signup page, allowing users to request the verification email again if needed.
2. **Verification Check on Login**:
- When a user attempts to log in, the system checks if their email is verified. If the email is not verified, the user is redirected to a `verification` page where they can verify their email. The email address is passed as a query parameter to the verification page.
3. **Automatic Deletion of Unverified Accounts**:
- Introduced a scheduled task (using `node-cron`) that runs every …

Implemented Email Resend on Signup, Verification Check on Login, and Automatic Deletion of Unverified Accounts

---

backend/index.js

Fixed CORS Setting for the backend

---

frontend/src/AgroShopAI/components/Pages/Admin-login.jsx

This PR introduces the Admin Login component to the project. The component includes a login form with email and password fields, validation logic, and user feedback for successful login or errors. The login form provides:
- **State Management:** Uses React `useState` hooks to manage the email, password, error messages, loading state, and the "remember me" checkbox.
- **Form Validation:** Includes client-side validation for email format and password strength.
- **Loading Spinner:** Displays a loading spinner while submitting the form to simulate authentication.
- **Error Handling:** Displays relevant error messages for empty fields, invalid credentials, or server-side validation issues.
- **Remember Me:** Implements functionality for users to opt-in to a "Remember Me" feature, which stores …

Add Admin Login Form with Validation and Enhanced Functionality

---

frontend/src/AgroShopAI/components/Pages/Admin-Dashboard.jsx
frontend/src/AgroShopAI/components/Pages/components/DashboardStats.jsx
frontend/src/AgroShopAI/components/Pages/components/GrievanceList.jsx
frontend/src/AgroShopAI/components/Pages/components/Header.jsx
frontend/src/AgroShopAI/components/Pages/components/Sidebar.jsx

This PR introduces the **Admin Dashboard** page, which allows administrators to manage user grievances, view detailed grievance information, and update the status of each grievance. The dashboard also includes additional components for monitoring crop yield forecasts, market price trends, and managing farmer support inquiries.
- **Sidebar Navigation**:
- Users can navigate through various sections such as **Dashboard**, **Grievances**, **Analytics**, **Customers**, **Sales**, and **Settings**.
- Responsive design to ensure compatibility across devices.
- **Grievances Management**:
- Displays a list of customer grievances with options to update their status.
- Status options include **Pending**, **Ongoing**, and **Solved**.
- Users can select the status from a dropdown and update it …

Add Admin Dashboard with Grievances Management and Enhanced Functionality

---

backend/controllers/shop/sub-controllers/shippingAddressController.js
backend/model/shop/sub-model/ShippingAddress.js

This PR introduces a comprehensive shipping address management system, allowing users to add, retrieve, update, and delete their saved shipping addresses, along with additional advanced functionalities. The updates support more robust address management, including setting default addresses, searching by fields, archiving, and filtering active addresses.
- Closes #867 
---
- **Fields:**
- **Address Line 1**: Required.
- **Address Line 2**: Optional.
- **City**: Required.
- **State**: Required.
- **Postal Code**: Required.
- **Country**: Required.
- **User Reference**: Associates each address with a specific user.
- **Additional Fields**:
- **isDefault**: Boolean to identify the default address for each user.
- **isArchived**: Boolean to flag addresses as archived (hidden …

Implement Shipping Address Schema and CRUD Operations with Advanced Features

---

backend/controllers/rent/RatingController.js
backend/index.js
backend/model/rent/rentProduct.js
backend/routes/rent/ratingRoutes.js
frontend/src/AgroRentAI/RentUserDashboard.jsx
frontend/src/AgroRentAI/components/RatingReviews.jsx
frontend/src/AgroRentAI/components/RentalHistory.jsx
frontend/src/AgroRentAI/components/Wishlist.jsx

Feedback for Rental Products
Wrote the backend API for creating reviews for products.
Modified the product schema to hold reviews in  one-to-many relationship schema.
Wrote conditional email sending on the basis of reviews of the users.
Created the frontend component to implement the purpose .
Toast notifications for success and errors messaging.
https://github.com/user-attachments/assets/a1161a3d-86d6-4494-a7b7-8fce1e282d53

Add reviews/feedback to rentals

---

backend/controllers/shop/sub-controllers/couponController.js
backend/middleware/sub-ware/validateCoupon.js
backend/model/shop/sub-model/couponModel.js
backend/routes/sub-routes/couponRoutes.js
backend/services/sub-service/couponValidator.js

This PR introduces the complete functionality for a **Discount and Coupon** system within the e-commerce platform. It includes:
- A **Coupon schema** to define the structure and behavior of coupons in the database.
- **Controllers** for managing coupon operations (create, update, delete, retrieve).
- **Middleware** to ensure the validity of coupons when applied to orders.
- **Utils** to handle common tasks like validating coupon eligibility and usage.
- Added a `Coupon` schema using Mongoose, with the following fields:
- `code`: A unique string representing the coupon code (e.g., `SAVE10`).
- `description`: A brief description of the coupon’s benefits.
- `discountType`: The type of discount (either `percentage` or `fixed`).
- `discountValue`: The value of the discount (e.g., `10` for 10% …

Added Coupon Discount System with Controllers, Schema, Middleware, and Utils

---

frontend/src/MainContent.jsx
frontend/src/components/AiChatbot.jsx
frontend/src/pages/Home.jsx

issue : #888 
https://github.com/user-attachments/assets/efcda8e6-f573-4e48-881a-8232cd4125b8
This PR adds an AI-powered chatbot to the AgroTech AI platform, 
enabling real-time assistance and improving user engagement by providing quick responses to questions related to agriculture. 
The chatbot is designed to support farmers and agricultural professionals by offering insights on crop management, soil health, pest control, and more.
- [ X] I have tested the changes locally
- [ X] Documentation has been updated (if necessary)
- [ X] Changes are backward-compatible

Integrate AI-Supported Chatbot for Enhanced User Assistance

---

frontend/src/components/GoTop.tsx
frontend/src/components/TestimonialSlider.jsx

issue : #887 
https://github.com/user-attachments/assets/a9dfa4d4-3142-4368-8452-8f53a8205bb6
Added auto scrollable good looking testimonial page to website
- [X ] I have tested the changes locally
- [ X] Documentation has been updated (if necessary)
- [ X] Changes are backward-compatible

Added testimonial with good UI

---

frontend/src/MainContent.jsx
frontend/src/components/DiscussionForum.jsx
frontend/src/components/Footer.jsx

issue : #889 
https://github.com/user-attachments/assets/f25aedd5-fd0c-4e7e-86d2-8a889dd8ce85
Implemented an interactive discussion forum that allows users to post and view questions and answers.
All Q&A data is securely stored in ensuring persistence even after page refreshes.
The design is fully responsive, offering a seamless experience across desktop, tablet, and mobile devices.
This feature makes it easier for users to engage in discussions, ask questions, and view answers without worrying about data loss.
- [X ] I have tested the changes locally
- [ X] Documentation has been updated (if necessary)
- [ X] Changes are backward-compatible

Interactive Discussion Forum with CURD operation & Responsive Design

---

frontend/src/AgroShopAI/components/Pages/SellerDashboard.jsx
frontend/src/AgroShopAI/components/Pages/components/SellerAnalyticsPage.jsx
frontend/src/AgroShopAI/components/Pages/components/SellerDashboardPage.jsx
frontend/src/AgroShopAI/components/Pages/components/SellerNav.jsx
frontend/src/AgroShopAI/components/Pages/components/SellerOrderManagementPage.jsx
frontend/src/AgroShopAI/components/Pages/components/SellerProductManagementPage.jsx
frontend/src/AgroShopAI/components/Pages/components/SellerSettingsPage.jsx
frontend/src/AgroShopAI/components/Pages/components/Sellerheader.jsx
frontend/src/MainContent.jsx

This PR introduces a comprehensive Seller Dashboard page, which includes the following sections:
- **Seller Dashboard:** Displays the seller's general information, including their name, store name, email, and account creation date. It also shows key statistics such as total earnings, active products, and recent orders.
- **Product Management:** Allows the seller to manage their products. Features include searching for products, adding new products, expanding product details for editing, and deleting products.
- **Order Management:** Displays the list of orders with relevant details such as order ID, date, status, and total amount.
- **Account Settings:** Provides an interface for the seller to update their store name, email, and password. …

Create Seller Dashboard Page with Product Management, Order Management, and Account Settings

---

backend/model/rent/rentProduct.js
frontend/src/AgroRentAI/RentAdminDashboard.jsx
frontend/src/AgroRentAI/RentUserDashboard.jsx
frontend/src/AgroRentAI/components/AdminAnalytics.jsx
frontend/src/AgroRentAI/components/AdminOrderManagement.jsx
frontend/src/AgroRentAI/components/AdminProductManagement.jsx
frontend/src/AgroRentAI/components/AdminUserManagement.jsx

Revamp the Admin Dash similar to the User Dash with separating components
Revamped the Admin page and separated the components.
Added separate components for options in the sidebar.
https://github.com/user-attachments/assets/ae9d8426-c83d-4c0f-a104-cc30c75e4205

Add admin dash components

---

frontend/src/pages/ContributorsPage.jsx

Contributors value showing wrong
Now the Contributors value is showing right.
Fixes #877 
Footer

Contributors value showing wrong

---

backend/controllers/rent/AdminUserController.js
backend/index.js
backend/model/user.js
backend/routes/rent/adminUserControlRoutes.js

Admin APIs for User Management
Admins have control over the user with the following APIs
CRUD Operations: Allow admins to create, update, delete, and view users.
Role and Permission Update: APIs to modify roles and permissions of users based on admin inputs.
Account Status Updates: Enable toggling account states (e.g., active, suspended).

Add admin user control APIs

---

frontend/src/MainContent.jsx
frontend/src/components/Navbar.jsx
frontend/src/components/models/WaterManagement.jsx

fix #827 
Added Sustainable Water Management Solutions Page
This PR introduces a new page to the AgroTech AI platform focused on Sustainable Water Management Solutions. The page aims to educate users on effective water conservation techniques and provides resources for implementing rainwater harvesting and other sustainable practices in agriculture.
1. Rainwater Harvesting Guides:
Comprehensive guides on setting up rainwater harvesting systems, including design, storage, and usage to maximize water collection and reduce dependency on external water sources.
2. Best Practices and Educational Resources:
Articles and tips on water conservation best practices tailored to agricultural applications.
Updated content on new technologies and methods for sustainable water management.
3. Responsive …

Added Sustainable Water Management Solutions Page | Issue #827

---

backend/model/user.js
frontend/src/AgroRentAI/components/AdminOrderManagement.jsx

Order Management from client
This PR creates and Implements 
Order Listing Page
Order Detail Page
Order Status Update Modals
Bulk Actions :UI elements like checkboxes to select multiple orders.
Toast notification for success and failure cases
Created and connected the frontend components with backend APIs for data fetching and processing.
Feature for selecting multiple products and updating in bulk at a time
https://github.com/user-attachments/assets/1bb897e9-f8dd-4d47-bf0d-472f869dc9a4

Implement order management from admin

---

backend/controllers/shop/sub-controllers/supplierController.js
backend/middleware/sub-ware/authSupplierMiddleware.js
backend/middleware/sub-ware/validationMiddleware.js
backend/model/shop/sub-model/Supplier.js
backend/routes/sub-routes/supplierRoutes.js

This PR introduces new backend functionality for managing suppliers, their associated products, and provides search and filtering capabilities. The changes include:
1. **Supplier Schema**: A new schema for suppliers, including relevant fields such as name, contact information, products supplied, and status.
2. **Product Management**: Routes and controllers for adding/removing products associated with a supplier.
3. **Search and Filter**: Endpoints to search suppliers by name, email, phone, and status.
4. **Middleware**: Validation middleware for incoming data and authorization middleware to restrict certain actions to admins only.
5. **New Routes**: API routes for all new functionality, including creation, retrieval, updating, and deletion of suppliers.
- **Models**:
- Added the …

AddedSupplier Management, Product Management, Search, and Filter Features to Backend

---

frontend/src/AgroShopAI/components/Pages/Affiliate.jsx
frontend/src/AgroShopAI/components/Pages/components/AffiliateDashboard.jsx
frontend/src/AgroShopAI/components/Pages/components/AffiliateHeader.jsx
frontend/src/AgroShopAI/components/Pages/components/AffiliateJoinSection.jsx
frontend/src/AgroShopAI/components/Pages/components/AffiliateMarketingMaterials.jsx
frontend/src/AgroShopAI/components/Pages/components/AffiliateTerms.jsx
frontend/src/MainContent.jsx

**Description**:
This PR introduces the full affiliate program page for AgroShop, consisting of three main components: the **header**, the **join section**, and the **marketing materials** section. This page serves as a hub for potential affiliates to learn about the program, sign up, and access marketing resources like banners and referral links. 
1. **Created `AffiliateHeader` Component**:
- Designed a sleek, branded header for the affiliate page with a prominent title and background color.
- The header helps set the tone of the page and aligns with the AgroShop brand aesthetics.
2. **Created `AffiliateJoinSection` Component**:
- Provides a clear, concise explanation of how the affiliate program works, including the benefits and step-by-step instructions for joining.
- Features a …

 Added Full Affiliate Program Page with Join Section and Marketing Materials

---

frontend/src/AgroShopAI/components/Pages/BulkPage.jsx
frontend/src/AgroShopAI/components/Pages/BundleCard.jsx
frontend/src/AgroShopAI/components/Pages/BundleData.js
frontend/src/AgroShopAI/components/Pages/BundleHeader.jsx
frontend/src/AgroShopAI/components/Pages/BundleList.jsx
frontend/src/AgroShopAI/components/Pages/BundleLoyaltyMessage.jsx
frontend/src/AgroShopAI/components/Pages/BundleOverview.jsx
frontend/src/AgroShopAI/components/Pages/BundlePriceBreakdown.jsx
frontend/src/AgroShopAI/components/Pages/BundleProductList.jsx
frontend/src/AgroShopAI/components/Pages/BundleRelatedItems.jsx
frontend/src/MainContent.jsx

**Description:**  
This PR introduces the `Bundle` page to the AgroShop platform, allowing users to explore curated product bundles with detailed price breakdowns and additional related product suggestions. This page is designed to enhance user engagement and promote cross-selling, featuring components for the main bundles, related bundles, and a loyalty promotion.
---
**Implemented Features:**
1. **BundleHeader Component**  
- A header with:
- A prominent title and subtitle
- A "Shop Now" button for quick navigation
- A cart icon for easy access to the shopping cart
- Stylish gradient background, hover effects, and transitions for an attractive look.
2. **FeaturedBundles Section**  
- Displays main product bundles with:
- Bundle titles, popularity indicators, and loyalty statuses
- Lists …

Added `Bundle` Page Component with Featured Product Bundles and Related Suggestions

---

backend/controllers/rent/AnalyticsController.js
backend/index.js
backend/model/rent/analytics.js
backend/routes/rent/analyticsRoutes.js

Implement analytics and reporting for Rentals
This PR adds deatiled analytics APIs with rigorous error loggins.
Added schema , routes and controllers for the purpose.
// Calculate total rentals, revenue, and rating for a product
router.get('/product-performance/:productId', productPerformace );
// Fetch rental insights by user
router.get('/user-insights/:userId', rentalInsights);
// Fetch rental statistics over time (e.g., weekly, monthly)
router.get('/rental-trends', rentalStats );
// Aggregate customer insights (top customers, most rentals, etc.)
router.get('/top-customers', topCustomers);
//updates/creates the analytics obj each time a API related to rentals is called
async function logRentalAnalytics(rental)
Footer

Add analytics APIs

---

backend/routes/rent/analyticsRoutes.js

FIx :  Backend Down due to Minor Spell Mistake in Rent Routes

---

backend/controllers/shop/sub-controllers/ticketController.js
backend/middleware/sub-ware/ticketMiddleware.js
backend/model/shop/sub-model/TIcket.js
backend/routes/sub-routes/ticketRoutes.js

This PR implements the support ticket system for users to create, manage, and track tickets. It includes the following features:
- **Ticket Schema:** Designed to store ticket information such as ticket ID, user ID, subject, description, status, priority, and timestamps.
- **Ticket Controller:** Logic to handle the creation, updating, and status tracking of tickets.
- **Middleware:** Middleware to ensure only authorized users can update ticket statuses and that users cannot modify tickets they do not own.
- **API Routes:** Defined RESTful routes to handle creating, fetching, updating, and assigning tickets.
- closes #963 
1. **Ticket Schema:**
- Created `Ticket` schema with the following fields:
- `ticketId`: Unique ID for each ticket.
- `userId`: ID of the user who created the ticket.
- …

Implemented Support Ticket System with CRUD Operations, Assignment, and Status Tracking

---

frontend/package-lock.json
frontend/package.json
frontend/src/AgroRentAI/RentUserDashboard.jsx
frontend/src/AgroRentAI/components/PersonalizationSettings.jsx
frontend/src/AgroRentAI/components/RentalReminders.jsx
frontend/src/AgroRentAI/components/sub-components/Recommendations.jsx

Dynamic Recommendations and Personalization
This PR adds the following features 
Related Product Recommendations: Suggest similar rental items based on the item currently being viewed or rented.
Personalized Dashboard: Display tailored recommendations based on user activity, rental history, or preferences.
Rental Reminders: Send users automated reminders before the return date or notify them about extension options.
https://github.com/user-attachments/assets/89d7d0b2-33a4-4e8a-aa77-0193f81ea77a

Add Personalization

---

backend/controllers/rent/RentOrderController.js
backend/routes/rent/rentOrderRoutes.js

Order History and Easy Re-Rentals APIs
This PR adds the following routes and controllers to the project.
//Get product rental history
router.get('/rent-product/history', getOrderHistory );
// Re-rent a previously rented item
router.post('rent-product/re-rent/:rentalId', reRent );
// Generate detailed rental receipt
router.get('rent-product/receipt/:rentalId', generateReceipt);

Order History and Easy Re-Rentals APIs

---

backend/middleware/authMiddleware.js
backend/routes/rent/rentCartRoutes.js
backend/routes/rent/rentProductRoutes.js
backend/routes/rent/rentWishlistRoutes.js

Authentication checks for AGRO-rent services
This PR modifies and optimizes the existing authMiddleware for better error logging.
Added checks to the routes so that non authenticated users are denied with proper message logging.

Add Authentication checks for AGRO-rent services

---

backend/middleware/authMiddleware.js
backend/routes/rent/rentCartRoutes.js
backend/routes/rent/rentProductRoutes.js
backend/routes/rent/rentWishlistRoutes.js

Reverts manikumarreddyu/AgroTech-AI#917

Revert "Add Authentication checks for AGRO-rent services"
